// lib/i18n/content/blogContent.ts
// Locale-aware blog content for the blog pages.

import type { Locale } from '../translations';

export interface BlogPostContentItem {
  slug: string;
  title: string;
  description: string;
  date: string;
  readTime: string;
  category: string;
  emoji: string;
  content: string;
}

export interface BlogPageContent {
  posts: BlogPostContentItem[];
}

const content: Partial<Record<Locale, BlogPageContent>> = {
  en: {
    posts: [
      { slug: 'visitor-management-without-hardware', title: 'How to manage society visitors without a hardware gate device', description: 'QR scanners and RFID systems cost ₹50,000+ per gate. Here is how modern societies manage visitor entry with just a smartphone app — and why it is actually more secure.', date: '2024-11-15', readTime: '7 min read', category: 'Security', emoji: '🚪', content: '## Visitor management without hardware\n\nModern societies can manage gate entry from a smartphone alone. Visitors can be invited with OTPs, walk-ins can be approved instantly, and trusted passes make daily domestic staff entry simple.\n\n### Why it works\n- No hardware purchase or maintenance\n- Better audit trail with timestamps\n- Faster approvals for guards and residents\n\n### Getting started\nRegister the society, add the guard, and the gate is ready in minutes.' },
      { slug: 'mygate-vs-societyapp-comparison', title: 'MyGate vs SocietyApp: Full comparison 2024', description: 'Switching from MyGate? Here is an honest comparison of pricing, features, hardware requirements, and what Indian societies actually care about.', date: '2024-11-08', readTime: '9 min read', category: 'Comparison', emoji: '⚖️', content: '## MyGate vs SocietyApp\n\nMyGate has strong brand awareness, but SocietyApp is often easier to adopt for smaller and mid-size societies because it works without hardware and starts with a free tier.\n\n### Where SocietyApp wins\n- No hardware required\n- Lower monthly cost for many societies\n- 6-language UI for residents and guards\n\n### Which one to choose\nChoose SocietyApp if you want speed, simplicity, and a free trial before commitment.' },
      { slug: 'collect-maintenance-fees-online', title: 'How to collect maintenance fees online from residents without chasing', description: 'Still sending WhatsApp messages asking residents to pay? Here is how to automate maintenance billing, get receipts automatically, and cut defaulters by 60%.', date: '2024-10-22', readTime: '6 min read', category: 'Finance', emoji: '💸', content: '## Digital maintenance billing\n\nA structured bill in the app removes the need for endless follow-up. Residents see the due date, the amount, and the breakdown in one place.\n\n### Benefits\n- Clear due dates\n- Automatic reminders\n- Digital receipts for residents\n- A live defaulter view for admins' },
      { slug: 'trusted-visitor-passes-maids-domestic-help', title: 'How to set up trusted visitor passes for maids and domestic help', description: 'Your maid comes every day at 8 AM. Should the security guard call you every single morning? Here is a smarter way to handle domestic staff entry.', date: '2024-10-10', readTime: '5 min read', category: 'Security', emoji: '🏠', content: '## Trusted passes for domestic staff\n\nTrusted passes remove repetitive gate calls and make daily entry predictable. The guard can check the visitor in with one tap while the resident gets a simple evening digest.\n\n### Setup steps\n1. Add the person as a trusted visitor\n2. Choose pass type and schedule\n3. Let the guard check them in quickly' },
    ],
  },
  hi: {
    posts: [
      { slug: 'visitor-management-without-hardware', title: 'हार्डवेयर गेट डिवाइस के बिना सोसायटी के विज़िटर कैसे मैनेज करें', description: 'QR स्कैनर और RFID सिस्टम प्रति गेट ₹50,000+ की लागत लेते हैं. यहाँ बताया गया है कि आधुनिक सोसायटियाँ सिर्फ एक स्मार्टफोन ऐप से विज़िटर एंट्री कैसे मैनेज करती हैं — और यह क्यों ज़्यादा सुरक्षित है।', date: '2024-11-15', readTime: '7 मिनट', category: 'सुरक्षा', emoji: '🚪', content: '## हार्डवेयर के बिना विज़िटर प्रबंधन\n\nआधुनिक सोसायटियाँ गेट एंट्री केवल एक स्मार्टफोन से मैनेज कर सकती हैं। विज़िटर को OTP से आमंत्रित किया जा सकता है, walk-in तुरंत अनुमोदित किए जा सकते हैं, और trusted passes रोज़मर्रा की घरेलू कर्मचारी एंट्री को आसान बना देते हैं।\n\n### यह क्यों काम करता है\n- कोई हार्डवेयर खरीद या रखरखाव नहीं\n- टाइमस्टैम्प के साथ बेहतर ऑडिट ट्रेल\n- गार्ड और रेजिडेंट्स के लिए तेज़ अनुमोदन' },
      { slug: 'mygate-vs-societyapp-comparison', title: 'MyGate बनाम SocietyApp: पूरी तुलना 2024', description: 'MyGate से स्विच कर रहे हैं? यहाँ कीमत, फीचर्स, हार्डवेयर ज़रूरतें और भारतीय सोसायटियों को वास्तव में क्या चिंता होती है, इसका ईमानदार तुलना है।', date: '2024-11-08', readTime: '9 मिनट', category: 'तुलना', emoji: '⚖️', content: '## MyGate बनाम SocietyApp\n\nMyGate का ब्रांड मजबूत है, लेकिन SocietyApp छोटे और मध्यम आकार की सोसायटियों के लिए आसान है क्योंकि यह हार्डवेयर के बिना काम करता है और फ्री टियर से शुरू होता है।' },
      { slug: 'collect-maintenance-fees-online', title: 'पीछा किए बिना रेजिडेंट्स से ऑनलाइन मेंटेनेंस फीस कैसे लें', description: 'क्या अभी भी WhatsApp पर संदेश भेजकर रेजिडेंट्स से पैसे मांग रहे हैं? यहाँ बताया गया है कि आप मेंटेनेंस बिलिंग को ऑटोमेटेड कैसे करें, रसीदें अपने आप कैसे लें, और डिफॉल्टर्स 60% तक कैसे कम करें।', date: '2024-10-22', readTime: '6 मिनट', category: 'वित्त', emoji: '💸', content: '## डिजिटल मेंटेनेंस बिलिंग\n\nऐप में एक संरचित बिल होने से अनगिनत follow-up की जरूरत खत्म हो जाती है। रेजिडेंट्स एक ही जगह पर ड्यू डेट, राशि और breakup देख सकते हैं।' },
      { slug: 'trusted-visitor-passes-maids-domestic-help', title: 'नौकरों और घरेलू कर्मचारियों के लिए trusted visitor passes कैसे सेट करें', description: 'आपकी नौकरानी हर दिन सुबह 8 बजे आती है. क्या सुरक्षा गार्ड हर सुबह आपको फोन करेगा? यहाँ घरेलू कर्मचारी एंट्री के लिए एक smarter तरीका है।', date: '2024-10-10', readTime: '5 मिनट', category: 'सुरक्षा', emoji: '🏠', content: '## घरेलू कर्मचारियों के लिए trusted passes\n\nTrusted passes दोहराव वाली गेट कॉल्स को हटाते हैं और दैनिक एंट्री को आसान बनाते हैं। गार्ड एक टैप में विज़िटर को चेक-इन कर सकता है, जबकि रेजिडेंट्स को सिर्फ एक शाम का digest मिलता है।' },
    ],
  },
  gu: {
    posts: [
      { slug: 'visitor-management-without-hardware', title: 'હાર્ડવેર ગેટ ડિવાઈસ વિના સોસાયટીના મુલાકાતીઓને કેવી રીતે મેનેજ કરવું', description: 'QR સ્કૅનર અને RFID સિસ્ટમો પ્રત્યેક ગેટ માટે ₹50,000+ કસોટી લે છે. અહીં બતાવ્યું છે કે આધુનિક સોસાયટીઓ ફક્ત એક સ્માર્ટફોન એપથી કેવી રીતે મુલાકાતી પ્રવેશનું સંચાલન કરે છે — અને તે કેમ ખરેખર વધુ સુરક્ષિત છે.', date: '2024-11-15', readTime: '7 મિનિટ', category: 'સુરક્ષા', emoji: '🚪', content: '## હાર્ડવેર વિના મુલાકાતી મેનેજમેન્ટ\n\nઆધુનિક સોસાયટીઓ ગેટ એન્ટ્રી ફક્ત એક સ્માર્ટફોનથી મેનેજ કરી શકે છે. મુલાકાતીઓને OTP દ્વારા આમંત્રણ આપી શકાય છે, walk-in તુરંત મંજૂર કરી શકાય છે, અને trusted passes દૈનિક घरेलુ સ્ટાફની એન્ટ્રીને સરળ બનાવે છે।' },
      { slug: 'mygate-vs-societyapp-comparison', title: 'MyGate বনામ SocietyApp: સંપૂર્ણ તુલના 2024', description: 'MyGateમાંથી બદલાવ着? અહીં ભાવ, ફીચર્સ, હાર્ડવેરની જરૂરિયાતો અને ભારતીય સોસાયટીઓને વાસ્તવમાં શું ચિંતા હોય છે, તેની ઈમાનદાર તુલના છે।', date: '2024-11-08', readTime: '9 મિનિટ', category: 'તુલના', emoji: '⚖️', content: '## MyGate বনામ SocietyApp\n\nMyGateનો બ્રાન્ડ મજબૂત છે, પણ SocietyApp નાના અને મધ્યમ કદની સોસાયટીઓ માટે સરળ છે કારણ કે તે હાર્ડવેર વિના કામ કરે છે અને ફ્રી ટાયરથી શરૂ થાય છે।' },
      { slug: 'collect-maintenance-fees-online', title: 'રેઝિડેન્ટ્સમાંથી અનુસંધાન વિના ઓનલાઇન જાળવણી ફી કેવી રીતે collect કરવી', description: 'શું તમે હજુ WhatsApp પર સુચના મોકલીને રેઝિડેન્ટ્સને ભરીત કરવા માંગો છો? અહીં બતાવ્યું છે કે તમે જાળવણી બિલિંગને ઓટોમેટેડ કેવી રીતે બનાવશો, રસીદો આપોઆપ કેવી રીતે મેળવો, અને ડિફોલ્ટર્સ 60% સુધી કેવી રીતે ઘટાડી શકો.', date: '2024-10-22', readTime: '6 મિનિટ', category: 'વित्त', emoji: '💸', content: '## ડિજિટલ જાળવણી બિલિંગ\n\nએપમાં એક સ્ટ્રક્ચર્ડ બિલ હોવો એટલે સતત ફોલો-અપની જરૂર સમાપ્ત થાય. રેઝિડેન્ટ્સ એક જ જગ્યાએ ડ્યૂ ડેટ, રકમ અને બ્રેકડાઉન જોઈ શકે છે.' },
      { slug: 'trusted-visitor-passes-maids-domestic-help', title: 'મૈડ અને ઘરના(STAFF) માટે trusted visitor passes કેવી રીતે સેટ કરવું', description: 'તમારી મૈડ હંમેશા સવારે 8 વાગે આવે છે. શું સુરક્ષા ગાર્ડ હંમેશા સવારમાં તમને કૉલ કરશે? અહીં ઘરેલુ સ્ટાફ માટે એક વધુ慧માર રીતે હલ છે।', date: '2024-10-10', readTime: '5 મિનિટ', category: 'સુરક્ષા', emoji: '🏠', content: '## ઘરના સ્ટાફ માટે trusted passes\n\nTrusted passes વારંવાર થતી ગેટ કૉલ્સને હટાવે છે અને દૈનિક એન્ટ્રીને સરળ બનાવે છે. ગાર્ડ એક ટૅપમાં આ વરિષ્ઠને ચેક-ઇન કરી શકે છે, જ્યારે રેઝિડેન્ટ્સને ફક્ત એક સાંજનો digest મળે છે।' },
    ],
  },
  ta: {
    posts: [
      { slug: 'visitor-management-without-hardware', title: 'வன்பொருள் கேட் சாதனம் இல்லாமல் சமுதாய விருந்தினர்களை எப்படி நிர்வகிப்பது', description: 'QR ஸ்கேனர்கள் மற்றும் RFID அமைப்புகள் ஒவ்வொரு கேட்டுக்கும் ₹50,000+ செலவு செய்கின்றன. இங்கே காட்டப்பட்டுள்ளபடி நவீன சமுதாயங்கள் ஒரு ஸ்மார்ட்போன் ஆப்பின் மூலம் விருந்தினர் நுழைவை எவ்வாறு நிர்வகிக்கின்றன — மற்றும் அது ஏன் உண்மையில் பாதுகாப்பானது.', date: '2024-11-15', readTime: '7 நிமிடங்கள்', category: 'பாதுகாப்பு', emoji: '🚪', content: '## வன்பொருள் இல்லாத விருந்தினர் மேலாண்மை\n\nநவீன சமுதாயங்கள் கேட் நுழைவை ஒரு ஸ்மார்ட்போனிலேயே நிர்வகிக்க முடியும். விருந்தினர்களை OTP-ஆக அழைக்கலாம், walk-in உடனே ஒப்புதல் அளிக்கலாம், மற்றும் trusted passes தினசரி வீட்டு ஊழியர் நுழைவை எளிதாக்குகின்றன.' },
      { slug: 'mygate-vs-societyapp-comparison', title: 'MyGate vs SocietyApp: முழு ஒப்பீடு 2024', description: 'MyGate-இலிருந்து மாறுகிறீர்களா? இங்கே விலை, அம்சங்கள், வன்பொருள் தேவைகள், மற்றும் இந்திய சமுதாயங்கள் உண்மையில் என்ன கவலைப்படுகின்றன என்பதற்கான நேர்மையான ஒப்பீடு உள்ளது.', date: '2024-11-08', readTime: '9 நிமிடங்கள்', category: 'ஒப்பீடு', emoji: '⚖️', content: '## MyGate vs SocietyApp\n\nMyGate-க்கு வலுவான பிராண்ட் அறிமுகம் உள்ளது, ஆனால் SocietyApp சிறிய மற்றும் நடுத்தர சமுதாயங்களுக்கு எளிதாக ஏற்றுக்கொள்ளக்கூடியது, ஏனெனில் அது வன்பொருள் இல்லாமல் வேலை செய்கிறது மற்றும் Free tier-ஆக தொடங்குகிறது.' },
      { slug: 'collect-maintenance-fees-online', title: 'குடியிருப்பாளர்களிடமிருந்து பின்தொடர்வின்றி ஆன்லைனில் பராமரிப்பு கட்டணங்களை எவ்வாறு வசூலிப்பது', description: 'இன்னும் WhatsApp செய்திகள் அனுப்பி குடியிருப்பாளர்களிடமிருந்து பணம் கேட்கிறீர்களா? இங்கே பராமரிப்பு பில்லிங்-ஐ ஆட்டோமேடிக் செய்வது, ரசீதுகளை தானாக பெறுவது மற்றும் டிஃபால்டர்களை 60% குறைப்பது எப்படி என்பதைக் காணலாம்.', date: '2024-10-22', readTime: '6 நிமிடங்கள்', category: 'நிதி', emoji: '💸', content: '## டிஜிட்டல் பராமரிப்பு பில்லிங்\n\nஆப்-இல் ஒரு கட்டமைக்கப்பட்ட பில் இருந்தால் எல்லா follow-up-களுக்கும் வேண்டிய அவசியமில்லை. குடியிருப்பாளர்கள் ஒரு இடத்தில் தான் due date, தொகை, breakdown-ஐ பார்க்க முடியும்.' },
      { slug: 'trusted-visitor-passes-maids-domestic-help', title: 'பணியாளர்கள் மற்றும் வீட்டு உதவியாளர்களுக்கான trusted visitor passes எவ்வாறு அமைப்பது', description: 'உங்கள் பணியாளர் ஒவ்வொரு நாளும் காலை 8 மணிக்கு வருகிறார். பாதுகாப்பு காவலர் ஒவ்வொரு காலை உங்களை அழைக்க வேண்டுமா? இங்கே வீட்டு ஊழியர் நுழைவுக்கான ஒரு சிறந்த வழி உள்ளது.', date: '2024-10-10', readTime: '5 நிமிடங்கள்', category: 'பாதுகாப்பு', emoji: '🏠', content: '## வீட்டு ஊழியர்களுக்கான trusted passes\n\nTrusted passes மீண்டும் மீண்டும் கேட் அழைப்புகளை நீக்கி தினசரி நுழைவை எளிதாக்குகின்றன. காவலர் ஒரு டேப்பில் விருந்தினரை check-in செய்யலாம், குடியிருப்பாளர் ஒரு எளிய மாலை digest பெறலாம்.' },
    ],
  },
  mr: {
    posts: [
      { slug: 'visitor-management-without-hardware', title: 'हार्डवेअर गेट डिव्हाइसशिवाय सोसायटीचे पाहुणे कसे व्यवस्थापित करावे', description: 'QR स्कॅनर्स आणि RFID सिस्टम्स प्रत्येक गेटसाठी ₹50,000+ खर्च करतात. येथे सांगितले आहे की आधुनिक सोसायट्या फक्त एक स्मार्टफोन अॅपने पाहुण्यांची एंट्री कशी व्यवस्थापित करतात — आणि ते का वास्तवात अधिक सुरक्षित असते.', date: '2024-11-15', readTime: '7 मिनिटे', category: 'सुरक्षा', emoji: '🚪', content: '## हार्डवेअरशिवाय पाहुणे व्यवस्थापन\n\nआधुनिक सोसायटी गेट एंट्री फक्त एका स्मार्टफोनने व्यवस्थापित करू शकतात. पाहुण्यांना OTPने आमंत्रित केले जाऊ शकते, walk-in त्वरित मंजूर केले जाऊ शकते, आणि trusted passes दररोजच्या घरगुती कर्मचाऱ्यांच्या एंट्रीला सोपी बनवतात.' },
      { slug: 'mygate-vs-societyapp-comparison', title: 'MyGate बनाम SocietyApp: संपूर्ण तुलना 2024', description: 'MyGateकडून बदलत आहात? येथे किंमत, फीचर्स, हार्डवेअर आवश्यकतां आणि भारतीय सोसायटींना खरंच काय काळजी वाटते याची विश्वासार्ह तुलना आहे.', date: '2024-11-08', readTime: '9 मिनिटे', category: 'तुलना', emoji: '⚖️', content: '## MyGate बनाम SocietyApp\n\nMyGateचे ब्रँड शक्तिशाली आहे, पण SocietyApp लहान आणि मध्यम सोसायटींसाठी सोपे आहे कारण ते हार्डवेअरशिवाय काम करते आणि फ्री टियरने सुरू होते.' },
      { slug: 'collect-maintenance-fees-online', title: 'रिझिडेंट्सकडून पाठलाग न करता ऑनलाइन मेंटेनन्स फी कशी वसूल करावी', description: 'आपण अजून WhatsApp संदेश पाठवून रिझिडेंट्सकडून पैसे मागत आहात? येथे सांगितले आहे की आपण मेंटेनन्स बिलिंग ऑटोमेटेड कसे कराल, रसीद्स आपोआप कसे मिळवाल, आणि डिफॉल्टर्स 60% पर्यंत कसे कमी कराल.', date: '2024-10-22', readTime: '6 मिनिटे', category: 'वित्त', emoji: '💸', content: '## डिजिटल मेंटेनन्स बिलिंग\n\nअॅपमध्ये संरचित बिल असल्याने अनंत फॉलो-अपची गरज संपते. रिझिडेंट्स एका ठिकाणीच due date, रक्कम आणि breakup पाहू शकतात.' },
      { slug: 'trusted-visitor-passes-maids-domestic-help', title: 'माईड आणि घरगुती सहाय्यकांसाठी trusted visitor passes कसे सेट करावे', description: 'तुमची माईड दररोज सकाळी 8 वाजता येते. सुरक्षा गार्ड दररोज सकाळी तुम्हाला फोन करणार का? येथे घरगुती कर्मचाऱ्यांच्या एंट्रीसाठी एक smarter मार्ग आहे.', date: '2024-10-10', readTime: '5 मिनिटे', category: 'सुरक्षा', emoji: '🏠', content: '## घरगुती कर्मचाऱ्यांसाठी trusted passes\n\nTrusted passes वारंवार होणाऱ्या गेट कॉल्स हटवून दररोजची एंट्री सोपी करतात. गार्ड एका टॅपमध्ये पाहुण्याला चेक-इन करू शकतो, तर रिझिडेंट्सला फक्त एक संध्याकाळी digest मिळतो.' },
    ],
  },
  pa: {
    posts: [
      { slug: 'visitor-management-without-hardware', title: 'ਹਾਰਡਵੇਅਰ ਗੇਟ ਡਿਵਾਈਸ ਬਿਨਾਂ ਸੋਸਾਈਟੀ ਦੇ ਵਿਜ਼ਟਰਾਂ ਦਾ ਇੰਤਜ਼ਾਮ ਕਿਵੇਂ ਕਰਾਂ', description: 'QR ਸਕੈਨਰ ਅਤੇ RFID ਸਿਸਟਮ ਹਰ ਗੇਟ ਲਈ ₹50,000+ ਖਰਚ ਕਰਦੇ ਹਨ. ਇੱਥੇ ਦਿਖਾਇਆ ਗਿਆ ਹੈ ਕਿ ਆਧੁਨਿਕ ਸੋਸਾਈਟੀਆਂ ਸਿਰਫ ਇੱਕ ਸਮਾਰਟਫ਼ੋਨ ਐਪ ਨਾਲ ਵਿਜ਼ਟਰ ਐਂਟਰੀ ਕਿਵੇਂ ਸੰਭਾਲਦੀਆਂ ਹਨ — ਅਤੇ ਇਹ ਅਸਲ ਵਿੱਚ ਕਿਉਂ ਵਧੇਰੇ ਸੁਰੱਖਿਅਤ ਹੈ।', date: '2024-11-15', readTime: '7 ਮਿੰਟ', category: 'ਸੁਰੱਖਿਆ', emoji: '🚪', content: '## ਹਾਰਡਵੇਅਰ ਬਿਨਾਂ ਵਿਜ਼ਟਰ ਮੈਨਿਜਮੈਂਟ\n\nਆਧੁਨਿਕ ਸੋਸਾਈਟੀਆਂ ਗੇਟ ਐਂਟਰੀ ਸਿਰਫ ਇੱਕ ਸਮਾਰਟਫ਼ੋਨ ਨਾਲ ਸੰਭਾਲ ਸਕਦੀਆਂ ਹਨ। ਵਿਜ਼ਟਰਾਂ ਨੂੰ OTP ਨਾਲ ਆਮਨਤਿਰ ਕਰ ਸਕਦੇ ਹਾਂ, walk-in ਨੂੰ ਤੁਰੰਤ ਮਨਜ਼ੂਰ ਕਰ ਸਕਦੇ ਹਾਂ, ਅਤੇ trusted passes ਰੋਜ਼ਾਨਾ ਘਰੇਲੂ ਸਟਾਫ਼ ਐਂਟਰੀ ਨੂੰ ਆਸਾਨ ਬਣਾ ਦਿੰਦੇ ਹਨ।' },
      { slug: 'mygate-vs-societyapp-comparison', title: 'MyGate ਬਨਾਮ SocietyApp: ਪੂਰਾ ਤੁਲਨਾ 2024', description: 'MyGate ਤੋਂ ਬਦਲ ਰਹੇ ਹੋ? ਇੱਥੇ ਕੀਮਤ, ਫੀਚਰ, ਹਾਰਡਵੇਅਰ ਲੋੜਾਂ ਅਤੇ ਭਾਰਤੀ ਸੋਸਾਈਟੀਆਂ ਨੂੰ ਅਸਲ ਵਿੱਚ ਕੀ ਚਿੰਤਾ ਹੈ, ਦੀ ਇਮਾਨਦਾਰ ਤੁਲਨਾ ਹੈ।', date: '2024-11-08', readTime: '9 ਮਿੰਟ', category: 'ਤੁਲਨਾ', emoji: '⚖️', content: '## MyGate ਬਨਾਮ SocietyApp\n\nMyGate ਦਾ ਬ੍ਰਾਂਡ ਮਜ਼ਬੂਤ ਹੈ, ਪਰ SocietyApp ਛੋਟੀਆਂ ਅਤੇ ਮੱਧਮ ਸਾਈਜ਼ ਦੀਆਂ ਸੋਸਾਈਟੀਆਂ ਲਈ ਆਸਾਨ ਹੈ ਕਿਉਂਕਿ ਇਹ ਹਾਰਡਵੇਅਰ ਬਿਨਾਂ ਕੰਮ ਕਰਦਾ ਹੈ ਅਤੇ ਫਰੀ ਟਾਇਰ ਨਾਲ ਸ਼ੁਰੂ ਹੋ ਜਾਂਦਾ ਹੈ।' },
      { slug: 'collect-maintenance-fees-online', title: 'ਰੇਜ਼ਿਡੈਂਟਾਂ ਤੋਂ ਪਿੱਛਾ ਕੀਤੇ ਬਿਨਾਂ ਆਨਲਾਈਨ ਵਿੱਚ ਮੈਨਿਟੇਨੈਂਸ ਫੀ ਕਿਵੇਂ ਵਸੂਲ ਕਰੀਏ', description: 'ਕੀ ਤੁਸੀਂ ਅਜੇ ਵੀ WhatsApp ਸੁਨੇਹੇ ਭੇਜ ਕੇ ਰੇਜ਼ਿਡੈਂਟਾਂ ਤੋਂ ਪੈਸੇ ਮੰਗ ਰਹੇ ਹੋ? ਇੱਥੇ ਦਿਖਾਇਆ ਗਿਆ ਹੈ ਕਿ ਤੁਸੀਂ ਮੈਨਿਟੇਨੈਂਸ ਬਿਲਿੰਗ ਨੂੰ ऑਟੋਮੈਟਿਕ ਕਿਵੇਂ ਬਣਾਉਂਦੇ ਹੋ, ਰਸੀਦਾਂ ਆਪਣੇ-ਆਪ ਕਿਵੇਂ ਲੈਂਦੇ ਹੋ, ਅਤੇ ਡਿਫਾਲਟਰਾਂ ਨੂੰ 60% ਤੱਕ ਕਿਵੇਂ ਘਟਾਉਂਦੇ ਹੋ।', date: '2024-10-22', readTime: '6 ਮਿੰਟ', category: 'ਵਿੱਤ', emoji: '💸', content: '## ਡਿਜ਼ਿਟਲ ਮੈਨਿਟੇਨੈਂਸ ਬਿਲਿੰਗ\n\nਐਪ ਵਿੱਚ ਇੱਕ ਸੰਰਚਿਤ ਬਿੱਲ ਹੋਣ ਨਾਲ ਅਣਗਿਣਤ ਫਾਲੋ-ਅਪ ਦੀ ਲੋੜ ਖਤਮ ਹੋ ਜਾਂਦੀ ਹੈ। ਰੇਜ਼ਿਡੈਂਟ ਇੱਕ ਸਥਾਨ ਤੇ ਹੀ due date, ਰਕਮ ਅਤੇ breakup ਦੇਖ ਸਕਦੇ ਹਨ।' },
      { slug: 'trusted-visitor-passes-maids-domestic-help', title: 'ਮਾਈਡ ਅਤੇ ਘਰੇਲੂ ਸਟਾਫ਼ ਲਈ trusted visitor passes ਕਿਵੇਂ ਸੈੱਟ ਕਰਨਾ ਹੈ', description: 'ਤੁਹਾਡੀ ਮਾਈਡ ਹਰ ਦਿਨ ਸਵੇਰ 8 ਵਜੇ ਆਂਦੀ ਹੈ। ਕੀ ਸੁਰੱਖਿਆ ਗਾਰਡ ਹਰ ਸਵੇਰ ਤੁਹਾਨੂੰ ਕਾਲ ਕਰੇਗਾ? ਇੱਥੇ ਘਰੇਲੂ ਸਟਾਫ਼ ਐਂਟਰੀ ਲਈ ਇੱਕ smarter ਤਰੀਕਾ ਹੈ।', date: '2024-10-10', readTime: '5 ਮਿੰਟ', category: 'ਸੁਰੱਖਿਆ', emoji: '🏠', content: '## ਘਰੇਲੂ ਸਟਾਫ਼ ਲਈ trusted passes\n\nTrusted passes ਦੁਹਰਾਏ ਜਾਣ ਵਾਲੇ ਗੇਟ ਕਾਲਾਂ ਨੂੰ ਹਟਾਉਂਦੀਆਂ ਹਨ ਅਤੇ ਰੋਜ਼ਾਨਾ ਐਂਟਰੀ ਨੂੰ ਆਸਾਨ ਬਣਾਉਂਦੀਆਂ ਹਨ। ਗਾਰਡ ਇੱਕ ਟੈਪ ਨਾਲ ਵਿਜ਼ਟਰ ਨੂੰ check-in ਕਰ ਸਕਦਾ ਹੈ, ਅਤੇ ਰੇਜ਼ਿਡੈਂਟ ਨੂੰ ਸਿਰਫ ਇੱਕ ਸ਼ਾਮ ਦਾ digest ਮਿਲਦਾ ਹੈ।' },
    ],
  },
};

export function getBlogContent(locale: Locale): BlogPageContent {
  return (content[locale] ?? content.en) as BlogPageContent;
}
