// lib/i18n/content/homeFeaturesContent.ts
// Locale-aware homepage feature/module teaser content.

import type { Locale } from '../translations';

export interface HomeFeatureModuleItem {
  icon: string;
  title: string;
  href: string;
  category: 'Security' | 'Finance' | 'Community' | 'Facilities' | 'Admin';
  tier: string;
  badge: string;
  badgeColor: string;
  desc: string;
  highlights: string[];
}

export interface HomeFeaturesContent {
  modules: HomeFeatureModuleItem[];
}

const content: Partial<Record<Locale, HomeFeaturesContent>> = {
  en: {
    modules: [
      { icon: '🚪', title: 'Visitor Management', href: '/features/visitor-management', category: 'Security', tier: 'Free', badge: 'Most Loved', badgeColor: 'bg-green/15 text-green', desc: 'OTP gate entry, pre-approved passes, trusted maids & drivers — full gate log with no hardware.', highlights: ['4 visitor flows', 'Zero hardware needed', 'Auto delivery exit timer'] },
      { icon: '👮', title: 'Security Guard Portal', href: '/features/visitor-management', category: 'Security', tier: 'Free', badge: '', badgeColor: '', desc: 'Dedicated UX for guards — walk-in logging, OTP verify, trusted-pass check-in.', highlights: ['Same app as residents', 'Walk-in + OTP flows', 'Real-time approvals'] },
      { icon: '💸', title: 'Maintenance & Billing', href: '/features/maintenance', category: 'Finance', tier: 'Free', badge: 'Free Tier', badgeColor: 'bg-teal/15 text-teal', desc: 'Auto-generate monthly bills, track payments via UPI/cash/NEFT, identify defaulters.', highlights: ['Auto bill generation', 'Defaulter report', 'Digital receipts'] },
      { icon: '📊', title: 'Payment Analytics', href: '/features/maintenance', category: 'Finance', tier: 'Standard', badge: '', badgeColor: '', desc: 'Collection rates, month-on-month trends, outstanding amounts at a glance.', highlights: ['Collection dashboard', 'Trend charts', 'Export reports'] },
      { icon: '📢', title: 'Notice Board', href: '/features/notices', category: 'Community', tier: 'Free', badge: '', badgeColor: '', desc: 'Pinned notices with push delivery, category tags (Urgent / Finance / Event), read receipts.', highlights: ['Push to all residents', '5 tag types', 'Pin & schedule'] },
      { icon: '🛠️', title: 'Issues & Complaints', href: '/features/issues', category: 'Community', tier: 'Standard', badge: '', badgeColor: '', desc: 'Raise complaints with photos, assign to vendors, track status from open to resolved.', highlights: ['Photo attachments', 'Vendor assignment', 'Full audit trail'] },
      { icon: '🎉', title: 'Events & Polls', href: '/features/events', category: 'Community', tier: 'Standard', badge: '', badgeColor: '', desc: 'Society events with RSVP, calendar export, photo galleries, and voting polls.', highlights: ['RSVP tracking', 'Anonymous polls', 'Photo gallery'] },
      { icon: '🗳️', title: 'Community Polls', href: '/features/events', category: 'Community', tier: 'Standard', badge: '', badgeColor: '', desc: 'Put society decisions to a vote — anonymous or named, with live result charts.', highlights: ['Anonymous voting', 'Live results', 'Multiple choice'] },
      { icon: '🤝', title: 'Community Help', href: '/features/community-help', category: 'Community', tier: 'Free', badge: '', badgeColor: '', desc: 'Neighbour-to-neighbour marketplace — share plumbers, tutors, cooks, and more.', highlights: ['8 help categories', 'Resident reviews', 'Post & respond'] },
      { icon: '🏊', title: 'Amenity Booking', href: '/features/amenities', category: 'Facilities', tier: 'Pro', badge: 'Pro', badgeColor: 'bg-amber/15 text-amber', desc: 'Book clubhouse, gym, or courts with time-slot selection, deposit handling, and admin approval.', highlights: ['Slot scheduler', 'Deposit collection', 'Admin approval flow'] },
      { icon: '🅿️', title: 'Parking Management', href: '/features/parking', category: 'Facilities', tier: 'Standard', badge: '', badgeColor: '', desc: 'Vehicle registry, slot allocation, guest parking permits, two-wheeler records.', highlights: ['Slot allocation', 'Guest permits', 'Vehicle registry'] },
      { icon: '👥', title: 'Member Management', href: '/features', category: 'Admin', tier: 'Free', badge: '', badgeColor: '', desc: 'Resident join approval, flat-to-member mapping, multiple members per flat.', highlights: ['Approval workflow', 'Flat mapping', 'Multi-family'] },
      { icon: '🛡️', title: 'Committee RBAC', href: '/features', category: 'Admin', tier: 'Free', badge: '', badgeColor: '', desc: 'Assign fine-grained permissions to Treasurer, Secretary, Security Head — each sees only what they need.', highlights: ['6 preset roles', 'Module-level permissions', 'Custom roles'] },
      { icon: '🔗', title: 'Invite Links & QR', href: '/features', category: 'Admin', tier: 'Free', badge: '', badgeColor: '', desc: 'Share a QR code or link to let residents self-register with society pre-filled. 7-day expiry.', highlights: ['QR code + link', 'Pre-filled form', '7-day validity'] },
      { icon: '🏘️', title: 'Multi-Society', href: '/features', category: 'Admin', tier: 'Free', badge: '', badgeColor: '', desc: 'One login to manage or live in multiple societies. Switch context with a tap.', highlights: ['Instant switch', 'Separate permissions', 'Unified inbox'] },
      { icon: '📦', title: 'Subscription Plans', href: '/pricing', category: 'Admin', tier: 'All', badge: '', badgeColor: '', desc: 'Free, Standard, Pro, and Enterprise plans — upgrade in-app, no sales call required.', highlights: ['Free forever tier', 'Monthly billing', 'Instant upgrade'] },
      { icon: '🔔', title: 'Push Notifications', href: '/features', category: 'Admin', tier: 'Free', badge: '', badgeColor: '', desc: 'Real-time alerts for visitor arrival, bill due, notice posted, complaint updated.', highlights: ['Instant delivery', 'Per-event control', 'Daily digest'] },
      { icon: '📋', title: 'Audit Log', href: '/features', category: 'Admin', tier: 'Standard', badge: '', badgeColor: '', desc: 'Tamper-evident activity log for every admin action — approve, reject, publish, delete.', highlights: ['Immutable log', 'Export CSV', 'Per-user filter'] },
      { icon: '🌐', title: 'Multilingual UI', href: '/features', category: 'Admin', tier: 'Free', badge: 'India-first', badgeColor: 'bg-amber/15 text-amber', desc: 'Full app in English, Hindi, Gujarati, Tamil, Marathi, and Punjabi.', highlights: ['6 languages', 'Instant switch', 'RTL-ready'] },
      { icon: '🏢', title: 'Society Registration', href: '/register', category: 'Admin', tier: 'Free', badge: '', badgeColor: '', desc: 'Secretary registers online, superadmin approves, credentials emailed instantly. Live in < 5 min.', highlights: ['Online registration', 'Auto approval email', 'Free to start'] },
      { icon: '⚙️', title: 'Profile & Settings', href: '/features', category: 'Admin', tier: 'Free', badge: '', badgeColor: '', desc: 'Notification preferences, language selector, password change, flat details — all in-app.', highlights: ['Notification control', 'Language switch', 'In-app settings'] },
      { icon: '📨', title: 'Notification Digest', href: '/features', category: 'Admin', tier: 'Free', badge: '', badgeColor: '', desc: 'Daily 9 PM digest for trusted visitor entries — one notification, not ten.', highlights: ['9 PM daily', 'Trusted visitors only', 'Reduces noise'] },
    ],
  },
  hi: {
    modules: [
      { icon: '🚪', title: 'विज़िटर प्रबंधन', href: '/features/visitor-management', category: 'Security', tier: 'फ्री', badge: 'सबसे पसंदीदा', badgeColor: 'bg-green/15 text-green', desc: 'OTP-आधारित गेट एंट्री, पहले से अनुमोदित पास, भरोसेमंद नौकर और ड्राइवर — बिना किसी हार्डवेयर के पूरी गेट लॉग।', highlights: ['4 विज़िटर फ्लो', 'कोई हार्डवेयर नहीं', 'ऑटो डिलीवरी एग्जिट टाइमर'] },
      { icon: '👮', title: 'सिक्योरिटी गार्ड पोर्टल', href: '/features/visitor-management', category: 'Security', tier: 'फ्री', badge: '', badgeColor: '', desc: 'गार्ड्स के लिए विशेष UX — वॉक-इन लॉगिंग, OTP सत्यापन, trusted-pass चेक-इन।', highlights: ['रेजिडेंट्स जैसा ही ऐप', 'वॉक-इन + OTP फ्लो', 'रीयल-टाइम अनुमोदन'] },
      { icon: '💸', title: 'मेंटेनेंस और बिलिंग', href: '/features/maintenance', category: 'Finance', tier: 'फ्री', badge: 'फ्री टियर', badgeColor: 'bg-teal/15 text-teal', desc: 'मासिक बिल अपने आप जनरेट करें, UPI/कैश/NEFT से पेमेंट ट्रैक करें, डिफॉल्टर्स पहचानें।', highlights: ['ऑटो बिल जनरेशन', 'डिफॉल्टर रिपोर्ट', 'डिजिटल रसीद'] },
      { icon: '📊', title: 'पेमेंट एनालिटिक्स', href: '/features/maintenance', category: 'Finance', tier: 'स्टैंडर्ड', badge: '', badgeColor: '', desc: 'कलेक्शन रेट, महीना-दर-महीना ट्रेंड, बकाया राशि एक ही नज़र में।', highlights: ['कलेक्शन डैशबोर्ड', 'ट्रेंड चार्ट', 'रिपोर्ट एक्सपोर्ट'] },
      { icon: '📢', title: 'नोटिस बोर्ड', href: '/features/notices', category: 'Community', tier: 'फ्री', badge: '', badgeColor: '', desc: 'पिन किए हुए नोटिस, पुश डिलीवरी, कैटेगरी टैग (तत्काल / वित्त / ईवेंट), रीड रसीद।', highlights: ['सभी रेजिडेंट्स तक पुश', '5 टैग प्रकार', 'पिन और शेड्यूल'] },
      { icon: '🛠️', title: 'इश्यूज़ और कंप्लेंट्स', href: '/features/issues', category: 'Community', tier: 'स्टैंडर्ड', badge: '', badgeColor: '', desc: 'फोटो के साथ कंप्लेंट दर्ज करें, वेंडर्स को असाइन करें, ओपन से रिज़ॉल्व्ड तक स्टेटस ट्रैक करें।', highlights: ['फोटो अटैचमेंट', 'वेंडर असाइनमेंट', 'पूर्ण ऑडिट ट्रेल'] },
      { icon: '🎉', title: 'इवेंट्स और पोल्स', href: '/features/events', category: 'Community', tier: 'स्टैंडर्ड', badge: '', badgeColor: '', desc: 'RSVP, कैलेंडर एक्सपोर्ट, फोटो गैलरी, और वोटिंग पोल्स के साथ सोसायटी इवेंट।', highlights: ['RSVP ट्रैकिंग', 'गुमनाम पोल्स', 'फोटो गैलरी'] },
      { icon: '🗳️', title: 'कम्युनिटी पोल्स', href: '/features/events', category: 'Community', tier: 'स्टैंडर्ड', badge: '', badgeColor: '', desc: 'सोसायटी के फैसले को वोट में बदलें — गुमनाम या नामित, लाइव रिजल्ट चार्ट के साथ।', highlights: ['गुमनाम वोटिंग', 'लाइव रिजल्ट', 'मल्टीपल-चॉइस'] },
      { icon: '🤝', title: 'कम्युनिटी हेल्प', href: '/features/community-help', category: 'Community', tier: 'फ्री', badge: '', badgeColor: '', desc: 'पड़ोसी-से-पड़ोसी मार्केटप्लेस — प्लंबर, ट्यूटर, रसोइया और बहुत कुछ साझा करें।', highlights: ['8 हेल्प कैटेगरी', 'रेजिडेंट रिव्यू', 'पोस्ट और रेस्पॉंड'] },
      { icon: '🏊', title: 'एमेंटी बुकिंग', href: '/features/amenities', category: 'Facilities', tier: 'प्रो', badge: 'प्रो', badgeColor: 'bg-amber/15 text-amber', desc: 'टाइम-स्लॉट चयन, डिपॉज़िट हैंडलिंग, और एडमिन अनुमोदन के साथ क्लबहाउस, जिम या कोर्ट बुक करें।', highlights: ['स्लॉट शेड्यूलर', 'डिपॉज़िट कलेक्शन', 'एडमिन अनुमोदन फ्लो'] },
      { icon: '🅿️', title: 'पार्किंग प्रबंधन', href: '/features/parking', category: 'Facilities', tier: 'स्टैंडर्ड', badge: '', badgeColor: '', desc: 'वाहन रजिस्टर, स्लॉट आवंटन, गेस्ट पार्किंग परमिट, दो-वीलर रिकॉर्ड।', highlights: ['स्लॉट आवंटन', 'गेस्ट परमिट', 'वाहन रजिस्टर'] },
      { icon: '👥', title: 'मेंबर प्रबंधन', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'रेजिडेंट्स की सदस्यता स्वीकृति, फ्लैट-से-मेम्बर मैपिंग, एक फ्लैट पर कई मेंबर।', highlights: ['स्वीकृति वर्कफ़्लो', 'फ्लैट मैपिंग', 'मल्टी-फैमिली'] },
      { icon: '🛡️', title: 'कमेटी RBAC', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'ट्रेज़रर, सेक्रेटरी, सिक्योरिटी हेड को सूक्ष्म अनुमतियाँ असाइन करें — हर किसी को सिर्फ वही दिखे जो चाहिए।', highlights: ['6 पूर्वनिर्धारित रोल', 'मॉड्यूल-लेवल परमिशन', 'कस्टम रोल'] },
      { icon: '🔗', title: 'इनवाइट लिंक और QR', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'QR कोड या लिंक शेयर करें ताकि रेजिडेंट्स अपने आप सोसायटी से पहले से भरा हुआ रजिस्टर कर सकें। 7 दिन की वैधता।', highlights: ['QR कोड + लिंक', 'पहले से भरा फॉर्म', '7-दिन वैधता'] },
      { icon: '🏘️', title: 'मल्टी-सोसायटी', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'एक लॉगिन से कई सोसायटियों का प्रबंधन या रहना। एक टैप से संदर्भ बदलें।', highlights: ['तत्काल स्विच', 'अलग परमिशन', 'एकीकृत इनबॉक्स'] },
      { icon: '📦', title: 'सब्सक्रिप्शन प्लान', href: '/pricing', category: 'Admin', tier: 'सभी', badge: '', badgeColor: '', desc: 'फ्री, स्टैंडर्ड, प्रो, और एंटरप्राइज़ प्लान — ऐप में अपग्रेड, कोई सेल्स कॉल नहीं।', highlights: ['हमेशा के लिए फ्री टियर', 'मासिक बिलिंग', 'तत्काल अपग्रेड'] },
      { icon: '🔔', title: 'पुश नोटिफिकेशन', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'विज़िटर आने, बिल देय, नोटिस पोस्ट, कंप्लेंट अपडेट के लिए रीयल-टाइम अलर्ट।', highlights: ['तत्काल डिलीवरी', 'प्रति-इवेंट नियंत्रण', 'दैनिक डाइजेस्ट'] },
      { icon: '📋', title: 'ऑडिट लॉग', href: '/features', category: 'Admin', tier: 'स्टैंडर्ड', badge: '', badgeColor: '', desc: 'हर एडमिन एक्शन के लिए टेम्पर-प्रूफ़ गतिविधि लॉग — अनुमोदन, अस्वीकृति, प्रकाशन, हटाना।', highlights: ['अपरिवर्तनीय लॉग', 'CSV एक्सपोर्ट', 'प्रति-यूज़र फ़िल्टर'] },
      { icon: '🌐', title: 'मल्टीलिंगुअल UI', href: '/features', category: 'Admin', tier: 'फ्री', badge: 'भारत-प्रथम', badgeColor: 'bg-amber/15 text-amber', desc: 'पूरी ऐप अंग्रेज़ी, हिंदी, गुजराती, तमिल, मराठी और पंजाबी में।', highlights: ['6 भाषाएँ', 'तत्काल स्विच', 'RTL तैयार'] },
      { icon: '🏢', title: 'सोसायटी रजिस्ट्रेशन', href: '/register', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'सेक्रेटरी ऑनलाइन रजिस्टर करते हैं, सुपरएडमिन अनुमोदन करते हैं, क्रेडेंशियल्स तुरंत ईमेल हो जाते हैं। 5 मिनट में लाइव।', highlights: ['ऑनलाइन रजिस्ट्रेशन', 'ऑटो अनुमोदन ईमेल', 'शुरू करने के लिए फ्री'] },
      { icon: '⚙️', title: 'प्रोफ़ाइल और सेटिंग्स', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'नोटिफिकेशन प्राथमिकताएँ, भाषा चयनकर्ता, पासवर्ड बदलना, फ्लैट विवरण — सब ऐप में।', highlights: ['नोटिफिकेशन नियंत्रण', 'भाषा स्विच', 'ऐप-इन सेटिंग्स'] },
      { icon: '📨', title: 'नोटिफिकेशन डाइजेस्ट', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'भरोसेमंद विज़िटर एंट्री के लिए दैनिक 9 PM डाइजेस्ट — एक नोटिफिकेशन, दस नहीं।', highlights: ['रोज़ 9 PM', 'केवल भरोसेमंद विज़िटर', 'शोर कम करता है'] },
    ],
  },
  gu: {
    modules: [
      { icon: '🚪', title: 'વીઝિટર મેનેજમેંટ', href: '/features/visitor-management', category: 'Security', tier: 'ફ્રી', badge: 'સૌથી વધુ પસંદ', badgeColor: 'bg-green/15 text-green', desc: 'OTP-આધારિત ગેટ એન્ટ્રી, સહેલાઈથી મંજૂર ચલો, વિશ્વસનીય maid અને drivers — હાર્ડવેર વિના સંપૂર્ણ ગેટ લોગ।', highlights: ['4 vizitor flws', 'હાર્ડવેરની જરૂર નહીં', 'ઓટો ડિલિવરી exit timer'] },
      { icon: '👮', title: 'સિક્યોરિટી ગાર્ડ પોર્ટલ', href: '/features/visitor-management', category: 'Security', tier: 'ફ્રી', badge: '', badgeColor: '', desc: 'ગાર્ડ્સ માટે વિશિષ્ટ UX — walk-in લોગિંગ, OTP ચેક, trusted-pass check-in.', highlights: ['રезидент્સ જેવી જ એપ', 'Walk-in + OTP flws', 'Realtime approvals'] },
      { icon: '💸', title: 'મેનેટેન્સ અને બિલિંગ', href: '/features/maintenance', category: 'Finance', tier: 'ફ્રી', badge: 'ફ્રી ટિયર', badgeColor: 'bg-teal/15 text-teal', desc: 'માસિક બિલ્સ આપમેળે બનાવો, UPI/કેશ/NEFT દ્વારા પેમેન્ટ ટ્રૅક કરો, defaulters ઓળખો.', highlights: ['ઓટો બિલ જનરેશન', 'ડિફોલ્ટર રિપોર્ટ', 'ડિજિટલ રસીદ'] },
      { icon: '📊', title: 'પેમેન્ટ એનાલિટિક્સ', href: '/features/maintenance', category: 'Finance', tier: 'સ્ટાન્ડર્ડ', badge: '', badgeColor: '', desc: 'કલેક્શન રેટ, મહિના-दીઠ ટ્રેન્ડ, બાકી રકમ એક નજરમાં.', highlights: ['કલેક્શન ડેશબોર્ડ', 'ટ્રેન્ડ ચાર્ટ્સ', 'રિપોર્ટ્સ એક્સપોર્ટ'] },
      { icon: '📢', title: 'નોટિસ બોર્ડ', href: '/features/notices', category: 'Community', tier: 'ફ્રી', badge: '', badgeColor: '', desc: 'પિન કરેલ નોટિસ, push ડિલિવરી, કેટેગરી ટૅગ, read-receipts.', highlights: ['બધા રેઝિડેન્ટ્સે સુધી push', '5 ટૅગ પ્રકાર', 'પિન અને શેડ્યૂલ'] },
      { icon: '🛠️', title: 'ઇશ્યુઝ અને કમ્પ્લેઇન્ટ્સ', href: '/features/issues', category: 'Community', tier: 'સ્ટાન્ડર્ડ', badge: '', badgeColor: '', desc: 'ફોટો સાથે કમ્પ્લેઇન્ટ્સ ઉઠાવો, vendorsને સોંપો, status open થી resolved સુધી ટ્રૅક કરો.', highlights: ['ફોટો એટેચમેન્ટ', 'વેન્ડર સોંપણી', 'સંપૂર્ણ ઓડિટ ટ્રેલ'] },
      { icon: '🎉', title: 'ઇવેંટ્સ અને પોલ્સ', href: '/features/events', category: 'Community', tier: 'સ્ટાન્ડર્ડ', badge: '', badgeColor: '', desc: 'RSVP, કેલેન્ડર એક્સપોર્ટ, ફોટો ગેલરી અને વોટિંગ પોલ્સ સાથે સોસાયટી ઇવેન્ટ્સ.', highlights: ['RSVP ટ્રેકિંગ', 'અનામત પોલ્સ', 'ફોટો ગેલરી'] },
      { icon: '🗳️', title: 'કમ્યુનિટી પોલ્સ', href: '/features/events', category: 'Community', tier: 'સ્ટાન્ડર્ડ', badge: '', badgeColor: '', desc: 'સોસાયટીનાં નિર્ણયોને વોટમાં ફેરવો — અનામત અથવા નામિત, live result charts સાથે.', highlights: ['અનામત વોટિંગ', 'લાઇવ રિઝલ્ટ', 'મલ્ટીપલ-ચોઇસ'] },
      { icon: '🤝', title: 'કમ્યુનિટી હેલ્પ', href: '/features/community-help', category: 'Community', tier: 'ફ્રી', badge: '', badgeColor: '', desc: 'પડોશીથી-પડોશી માર્કેટપ્લેસ — प्लમ્બર, ટ્યૂટર, કુક, અને વધુ શેર કરો.', highlights: ['8 હેલ્પ કેટેગરીઝ', 'રેઝિડેન્ટ રિવ્યૂઝ', 'પોસ્ટ અને જવાબ'] },
      { icon: '🏊', title: 'એમેનિટી બુકિંગ', href: '/features/amenities', category: 'Facilities', tier: 'પ્રો', badge: 'પ્રો', badgeColor: 'bg-amber/15 text-amber', desc: 'ટાઇમ-સ્લોટ સિલેક્શન, ડિપોઝિટ હેન્ડલિંગ અને એડમિન મંજૂરી સાથે ક્લબહાઉસ, જીમ અથવા કોર્ટ બુક કરો.', highlights: ['સ્લોટ શેડ્યૂલર', 'ડિપોઝિટ કલેક્શન', 'એડમિન મંજૂરી ફ્લો'] },
      { icon: '🅿️', title: 'પાર્કિંગ મેનેજમેન્ટ', href: '/features/parking', category: 'Facilities', tier: 'સ્ટાન્ડર્ડ', badge: '', badgeColor: '', desc: 'વાહન રજીસ્ટ્રી, સ્લોટ અલોકન, ગેસ્ટ પાર્કિંગ પરમીટ, બે-વ્હીલર રેકોર્ડ.', highlights: ['સ્લોટ અલોકન', 'ગેસ્ટ પરમીટ', 'વાહન રજીસ્ટ્રી'] },
      { icon: '👥', title: 'મેમ્બર મેનેજમેન્ટ', href: '/features', category: 'Admin', tier: 'ફ્રી', badge: '', badgeColor: '', desc: 'રેઝિડેન્ટ જોડાણ મંજૂરી, ફ્લેટ-થી-મેમ્બર મેપિંગ, એક ફ્લેટ પર multiple members.', highlights: ['મંજૂરી વર્કફ્લો', 'ફ્લેટ મેપિંગ', 'મલ્ટી-ફેમિલી'] },
      { icon: '🛡️', title: 'કમિટી RBAC', href: '/features', category: 'Admin', tier: 'ફ્રી', badge: '', badgeColor: '', desc: 'ટ્રેઝરર, સેક્રેટરી, સિક્યોરિટી હેડને fine-grained પરમિશન્સ સોંપો — દરેકને ફક્ત તે જ જોઈએ જે જરૂરી હોય.', highlights: ['6 preset roles', 'Module-level permissions', 'Custom roles'] },
      { icon: '🔗', title: 'આમંત્રણ લિંક્સ અને QR', href: '/features', category: 'Admin', tier: 'ફ્રી', badge: '', badgeColor: '', desc: 'QR code અથવા link શેર કરો જેથી રેઝિડેન્ટ્સ પોતે જ સોસાયટી સાથે pre-filled self-register કરી શકે. 7-day expiry.', highlights: ['QR code + link', 'Pre-filled form', '7-day validity'] },
      { icon: '🏘️', title: 'મલ્ટી-સોસાયટી', href: '/features', category: 'Admin', tier: 'ફ્રી', badge: '', badgeColor: '', desc: 'એક લોગિનથી multiple societies მართો અથવા فيها રહો. એક ટૅપથી કન્ટેક્ષ્ટ બદલો.', highlights: ['Instant switch', 'Separate permissions', 'Unified inbox'] },
      { icon: '📦', title: 'સબ્સ્ક્રિપ્શન પ્લાન', href: '/pricing', category: 'Admin', tier: 'બધા', badge: '', badgeColor: '', desc: 'ફ્રી, સ્ટાન્ડર્ડ, પ્રો અને એન્ટરપ્રાઈઝ પ્લાન — in-app અપગ્રેડ, no sales call.', highlights: ['ફ્રી ફોરઅવે ટિયર', 'માસિક બિલિંગ', 'તાત્કાલિક અપગ્રેડ'] },
      { icon: '🔔', title: 'પુશ નોટિફિકેશન્સ', href: '/features', category: 'Admin', tier: 'ફ્રી', badge: '', badgeColor: '', desc: 'વીઝિટર આવો, બિલ પેડું, નોટિસ પોસ્ટ, કમ્પ્લેઇન્ટ અપડેટ માટે real-time alerted.', highlights: ['તાત્કાલિક ડિલિવરી', 'Per-event control', 'દૈનિક ડાઈજેસ્ટ'] },
      { icon: '📋', title: 'ઓડிட લોગ', href: '/features', category: 'Admin', tier: 'સ્ટાન્ડર્ડ', badge: '', badgeColor: '', desc: 'દરેક એડમિન એક્શન માટે tamper-evident activity log — approve, reject, publish, delete.', highlights: ['Immutable log', 'Export CSV', 'Per-user filter'] },
      { icon: '🌐', title: 'મલ્ટીલિંગુઅલ UI', href: '/features', category: 'Admin', tier: 'ફ્રી', badge: 'ભારત-પ્રથમ', badgeColor: 'bg-amber/15 text-amber', desc: 'સંપૂર્ણ એપ ઇંગ્લિશ, હિન્દી, ગુજરાતી, તામિલ, મરાઠી અને પંજાબીમાં.', highlights: ['6 languages', 'Instant switch', 'RTL-ready'] },
      { icon: '🏢', title: 'સોસાયટી રજીસ્ટ્રેશન', href: '/register', category: 'Admin', tier: 'ફ્રી', badge: '', badgeColor: '', desc: 'સેક્રેટરી ઓનલાઈન રજીસ્ટર કરે છે, સુપરએડમિન મંજૂરી આપે છે, credentials તાત્કાલિક ઇમેઇલ થાય છે. 5 મિનિટમાં લાઇવ.', highlights: ['Online registration', 'Auto approval email', 'Free to start'] },
      { icon: '⚙️', title: 'પ્રોફાઇલ અને સેટિંગ્સ', href: '/features', category: 'Admin', tier: 'ફ્રી', badge: '', badgeColor: '', desc: 'નોટિફિકેશન પસંદગીઓ, ભાષા સિલેક્ટર, પાસવર્ડ બદલવું, ફ્લેટ વિગતો — બધું In-app.', highlights: ['Notification control', 'Language switch', 'In-app settings'] },
      { icon: '📨', title: 'નોટિફિકેશન ડાઈજેસ્ટ', href: '/features', category: 'Admin', tier: 'ફ્રી', badge: '', badgeColor: '', desc: 'વિશ્વસનીય vizitor entries માટે દૈનિક 9 PM ડાઈજેસ્ટ — એક નોટિફિકેશન, દસ નહીં.', highlights: ['9 PM daily', 'Trusted visitors only', 'Reduces noise'] },
    ],
  },
  ta: {
    modules: [
      { icon: '🚪', title: 'விசிட்டர் மேலாண்மை', href: '/features/visitor-management', category: 'Security', tier: 'இலவசம்', badge: 'அதிக விரும்பப்பட்டது', badgeColor: 'bg-green/15 text-green', desc: 'OTP அடிப்படையிலான கேட் நுழைவு, முன்-அங்கீகரிக்கப்பட்ட பாஸ்கள், நம்பகமானmaids & drivers — வன்பொருள் இல்லாமலே முழு கேட் பதிவு.', highlights: ['4 விசிட்டர் ஃப்ளோக்கள்', 'வன்பொருள் தேவையில்லை', 'ஆட்டோ டெலிவரி வெளியேறும் நேரம்'] },
      { icon: '👮', title: 'சேஃப்டி கார்டு போர்டல்', href: '/features/visitor-management', category: 'Security', tier: 'இலவசம்', badge: '', badgeColor: '', desc: 'கார்டுகளுக்கான சிறப்பு UX — walk-in பதிவு, OTP சரிபார்ப்பு, trusted-pass check-in.', highlights: ['வசிப்பாளர்களுக்கான அதே ஆப்', 'Walk-in + OTP flws', 'நேரடி அங்கீகாரம்'] },
      { icon: '💸', title: 'பராமரிப்பு & பிலிங்', href: '/features/maintenance', category: 'Finance', tier: 'இலவசம்', badge: 'இலவசம்', badgeColor: 'bg-teal/15 text-teal', desc: 'மாதாந்திர பில்களை தானாக உருவாக்குங்கள், UPI/காசு/NEFT மூலம் பணம் கண்காணிக்கவும், defaulters கண்டறியவும்.', highlights: ['ஆட்டோ பில் ஜெனரேஷன்', 'டிஃபால்டர் அறிக்கை', 'டிஜிட்டல் ரசீது'] },
      { icon: '📊', title: 'பேமெண்ட் அனலிடிக்ஸ்', href: '/features/maintenance', category: 'Finance', tier: 'ஸ்டாண்டர்ட்', badge: '', badgeColor: '', desc: 'சேகரிப்பு விகிதம், மாதம்தோறும் போக்குகள், நிலுவைத் தொகை ஒரு பார்வையில்.', highlights: ['கேலெக்ஷன் டாஷ்போர்டு', 'ட்ரெண்ட் சாட்கள்', 'ரிப்போர்ட் எக்ஸ்போர்ட்'] },
      { icon: '📢', title: 'நோடிஸ் போர்டு', href: '/features/notices', category: 'Community', tier: 'இலவசம்', badge: '', badgeColor: '', desc: 'பின் செய்யப்பட்ட அறிவிப்புகள், push டெலிவரி, வகை டேக்ஸ், read-receipts.', highlights: ['அனைத்து குடியிருப்பாளர்களுக்கும் push', '5 டேக் வகைகள்', 'பின் & ஷெட்யூல்'] },
      { icon: '🛠️', title: 'சிக்கல்கள் & புகார்கள்', href: '/features/issues', category: 'Community', tier: 'ஸ்டாண்டர்ட்', badge: '', badgeColor: '', desc: 'புகைப்படங்களுடன் புகார்களை சமர்ப்பிக்கவும், vendors-க்கு ஒதுக்கவும், open முதல் resolved வரை நிலை கண்காணிக்கவும்.', highlights: ['புகைப்பட இணைப்புகள்', 'வெண்டர் ஒதுக்கீடு', 'முழு ஆக்டிட் ட்ரெயில்'] },
      { icon: '🎉', title: 'நிகழ்ச்சிகள் & வாக்கெடுப்புகள்', href: '/features/events', category: 'Community', tier: 'ஸ்டாண்டர்ட்', badge: '', badgeColor: '', desc: 'RSVP, காலெண்டர் ஏக்ஸ்போர்ட், புகைப்பட கேலரி மற்றும் வோட்டிங் போல்ஸ் உடன் சமுதாய நிகழ்ச்சிகள்.', highlights: ['RSVP கண்காணிப்பு', 'அநாமதேய வாக்கெடுப்புகள்', 'புகைப்பட கேலரி'] },
      { icon: '🗳️', title: 'கம்யூனிட்டி போல்ஸ்', href: '/features/events', category: 'Community', tier: 'ஸ்டாண்டர்ட்', badge: '', badgeColor: '', desc: 'சமுதாய முடிவுகளை வாக்கெடுப்பில் கொண்டு வாருங்கள் — அநாமதேயமாக அல்லது பெயருடன், live result charts உடன்.', highlights: ['அநாமதேய வாக்குப்பதிவு', 'லைவ் ரிசல்ட்ஸ்', 'மல்டிபிள்-சாய்ஸ்'] },
      { icon: '🤝', title: 'கம்யூனிட்டி ஹெல்ப்', href: '/features/community-help', category: 'Community', tier: 'இலவசம்', badge: '', badgeColor: '', desc: 'அயலார்-அயலார் சந்தை — பிளம்பர்கள், டியூட்டர்கள், குக்குகள் மற்றும் இன்னும் பலவற்றை பகிரவும்.', highlights: ['8 ஹெல்ப் கேடகிரியாஸ்', 'வசிப்பாளர் மறுமொழிகள்', 'போஸ்ட் & ரிஸ்பாண்ட்'] },
      { icon: '🏊', title: 'அமைப்புப் புத்தகம்', href: '/features/amenities', category: 'Facilities', tier: 'ப்ரோ', badge: 'ப்ரோ', badgeColor: 'bg-amber/15 text-amber', desc: 'டைம்-ஸ்லாட் தேர்வு, டெபாசிட் கையாளுதல், நிர்வாக ஒப்புதல் மூலம் கிளப் ஹவுஸ், ஜிம் அல்லது கோர்ட்டுகளை முன்பதிவு செய்யவும்.', highlights: ['ஸ்லாட் ஷெட்யூலர்', 'டெபாசிட் சேகரிப்பு', 'நிர்வாக ஒப்புதல் ஓட்டம்'] },
      { icon: '🅿️', title: 'பார்க்கிங் மேலாண்மை', href: '/features/parking', category: 'Facilities', tier: 'ஸ்டாண்டர்ட்', badge: '', badgeColor: '', desc: 'வாகன பதிவு, ஸ்லாட் ஒதுக்கீடு, விருந்தினர் பார்க்கிங் பாஸ்கள், இரு சக்கர பதிவுகள்.', highlights: ['ஸ்லாட் ஒதுக்கீடு', 'விருந்தினர் பாஸ்கள்', 'வாகன பதிவு'] },
      { icon: '👥', title: 'உறுப்பினர் மேலாண்மை', href: '/features', category: 'Admin', tier: 'இலவசம்', badge: '', badgeColor: '', desc: 'வசிப்பாளர் சேருதல் ஒப்புதல், flat-to-member mapping, ஒவ்வொரு ஃப்ளாட்டிலும் பல உறுப்பினர்கள்.', highlights: ['ஒப்புதல் workflow', 'ஃப்ளாட் மேப்பிங்', 'மல்டி-பேமிலி'] },
      { icon: '🛡️', title: 'கமிட்டி RBAC', href: '/features', category: 'Admin', tier: 'இலவசம்', badge: '', badgeColor: '', desc: 'ட்ரெஷரர், செயலாளர், பாதுகாப்பு தலைவர் ஆகியோருக்கு நுணுக்க அனுமதிகளை ஒதுக்கவும் — ஒவ்வொருவரும் வேண்டியதை மட்டும் பார்ப்பார்கள்.', highlights: ['6 preset roles', 'Module-level permissions', 'Custom roles'] },
      { icon: '🔗', title: 'அழைப்புக் கோடுகள் & QR', href: '/features', category: 'Admin', tier: 'இலவசம்', badge: '', badgeColor: '', desc: 'QR code அல்லது link பகிரவும், இதனால் குடியிருப்பாளர்கள் தானாகவே pre-filled self-register செய்து கொள்ளலாம். 7 நாள் செல்லுபடியாகும்.', highlights: ['QR code + link', 'Pre-filled form', '7-day validity'] },
      { icon: '🏘️', title: 'மல்டி-சோசைட்டி', href: '/features', category: 'Admin', tier: 'இலவசம்', badge: '', badgeColor: '', desc: 'ஒரே லாகின் மூலம் பல சோசைட்டிகளை நிர்வகிக்கவும் அல்லது வாழவும். ஒரு டாப்பில் context மாற்றவும்.', highlights: ['Instant switch', 'Separate permissions', 'Unified inbox'] },
      { icon: '📦', title: 'சப்ஸ்கிரிப்ஷன் திட்டங்கள்', href: '/pricing', category: 'Admin', tier: 'அனைத்தும்', badge: '', badgeColor: '', desc: 'இலவசம், ஸ்டாண்டர்ட், ப்ரோ மற்றும் எண்டர்பிரைஸ் திட்டங்கள் — ஆப்-உடனே அப்கிரேடு, விற்பனை அழைப்பு தேவையில்லை.', highlights: ['Free forever tier', 'மாதாந்திர பிலிங்', 'உடனடி அப்கிரேட்'] },
      { icon: '🔔', title: 'புஷ் அறிவிப்புகள்', href: '/features', category: 'Admin', tier: 'இலவசம்', badge: '', badgeColor: '', desc: 'விசிட்டர் வருகை, பில் தேதியானது, நோடிஸ் இடப்பட்டது, புகார் புதுப்பிக்கப்பட்டது என real-time alerts.', highlights: ['உடனடி டெலிவரி', 'Per-event control', 'தினசரி டைஜஸ்ட்'] },
      { icon: '📋', title: 'ஆடிட் லாக்', href: '/features', category: 'Admin', tier: 'ஸ்டாண்டர்ட்', badge: '', badgeColor: '', desc: 'ஒவ்வொரு நிர்வாக செயலும் tamper-evident activity log — approve, reject, publish, delete.', highlights: ['Immutable log', 'Export CSV', 'Per-user filter'] },
      { icon: '🌐', title: 'மல்டிலிங்குவல் UI', href: '/features', category: 'Admin', tier: 'இலவசம்', badge: 'இந்தியா-முதல்', badgeColor: 'bg-amber/15 text-amber', desc: 'முழு ஆப் ஆங்கிலம், இந்தி, குஜராத்தி, தமிழ், மராத்தி மற்றும் பஞ்சாபி ஆகியவற்றில்.', highlights: ['6 மொழிகள்', 'உடனடி மாற்றம்', 'RTL தயாராக'] },
      { icon: '🏢', title: 'சமுதாய பதிவு', href: '/register', category: 'Admin', tier: 'இலவசம்', badge: '', badgeColor: '', desc: 'செயலாளர் ஆன்லைனில் பதிவு செய்கிறார், சூப்பர் அட்மின் ஒப்புதல் அளிக்கிறார், credentials உடனடியாக மின்னஞ்சல் ஆகும். 5 நிமிடங்களில் லைவ்.', highlights: ['Online registration', 'Auto approval email', 'Free to start'] },
      { icon: '⚙️', title: 'சுயவிவரம் & அமைப்புகள்', href: '/features', category: 'Admin', tier: 'இலவசம்', badge: '', badgeColor: '', desc: 'அறிவிப்பு விருப்பங்கள், மொழி தேர்வி, கடவுச்சொல் மாற்றம், ஃப்ளாட் விவரங்கள் — அனைத்தும் in-app.', highlights: ['Notification control', 'Language switch', 'In-app settings'] },
      { icon: '📨', title: 'அறிவிப்பு டைஜஸ்ட்', href: '/features', category: 'Admin', tier: 'இலவசம்', badge: '', badgeColor: '', desc: 'நம்பகமான விசிட்டர் உள்ளீடுகளுக்காக தினசரி 9 PM டைஜஸ்ட் — ஒரு அறிவிப்பு, பத்து அல்ல.', highlights: ['9 PM daily', 'Trusted visitors only', 'Reduces noise'] },
    ],
  },
  mr: {
    modules: [
      { icon: '🚪', title: 'विजिटर व्यवस्थापन', href: '/features/visitor-management', category: 'Security', tier: 'फ्री', badge: 'सर्वाधिक पसंद', badgeColor: 'bg-green/15 text-green', desc: 'OTP-आधारित गेट एंट्री, अगोदर मंजूर केलेले पास, विश्वासार्ह maid आणि drivers — हार्डवेअर न सोडता संपूर्ण गेट लॉग.', highlights: ['4 विजिटर फ्लो', 'हार्डवेअरची गरज नाही', 'ऑटो डिलिव्हरी एग्झिट टाइमर'] },
      { icon: '👮', title: 'सिक्युरिटी गार्ड पोर्टल', href: '/features/visitor-management', category: 'Security', tier: 'फ्री', badge: '', badgeColor: '', desc: 'गार्डसाठी वेगळा UX — walk-in लॉगिंग, OTP पडताळणी, trusted-pass check-in.', highlights: ['निवासींसारखेच अॅप', 'Walk-in + OTP फ्लो', 'रिअल-टाइम मंजुरी'] },
      { icon: '💸', title: 'देखभाल आणि बिलिंग', href: '/features/maintenance', category: 'Finance', tier: 'फ्री', badge: 'फ्री टियर', badgeColor: 'bg-teal/15 text-teal', desc: 'मासिक बिल्स आपोआप तयार करा, UPI/नगदी/NEFTने पेमेंट ट्रॅक करा, डिफॉल्टर्स ओळखा.', highlights: ['ऑटो बिल जनरेशन', 'डिफॉल्टर रिपोर्ट', 'डिजिटल रसीद'] },
      { icon: '📊', title: 'पेमेंट अॅनालिटिक्स', href: '/features/maintenance', category: 'Finance', tier: 'स्टँडर्ड', badge: '', badgeColor: '', desc: 'कलेक्शन रेट, महिन्याने बदलणारे ट्रेंड, उर्वरित रक्कम एकाच नजरेत.', highlights: ['कलेक्शन डॅशबोर्ड', 'ट्रेंड चार्ट्स', 'रिपोर्ट एक्सपोर्ट'] },
      { icon: '📢', title: 'नोटिस बोर्ड', href: '/features/notices', category: 'Community', tier: 'फ्री', badge: '', badgeColor: '', desc: 'पिन केलेली नोटिस, push डिलिव्हरी, श्रेणी टॅग, read-receipts.', highlights: ['सर्व रहिवाशांपर्यंत push', '5 टॅग प्रकार', 'पिन आणि शेड्यूल'] },
      { icon: '🛠️', title: 'आवाजे आणि तक्रारी', href: '/features/issues', category: 'Community', tier: 'स्टँडर्ड', badge: '', badgeColor: '', desc: 'फोटोसह तक्रारी नोंदवा, vendorsना असाइन करा, open ते resolved पर्यंत स्थिती ट्रॅक करा.', highlights: ['फोटो अटॅचमेंट', 'वेंडर असाइनमेंट', 'पूर्ण ऑडिट ट्रेल'] },
      { icon: '🎉', title: 'इव्हेंट्स आणि पोल्स', href: '/features/events', category: 'Community', tier: 'स्टँडर्ड', badge: '', badgeColor: '', desc: 'RSVP, कॅलेंडर एक्सपोर्ट, फोटो गॅलरी आणि वोटिंग पोल्ससह सोसायटी इव्हेंट्स.', highlights: ['RSVP ट्रॅकिंग', 'अनामिक पोल्स', 'फोटो गॅलरी'] },
      { icon: '🗳️', title: 'कम्युनिटी पोल्स', href: '/features/events', category: 'Community', tier: 'स्टँडर्ड', badge: '', badgeColor: '', desc: 'सोसायटीचे निर्णय votementमध्ये रूपांतरित करा — अनामिक किंवा नावाने, live result charts सह.', highlights: ['अनामिक मतदान', 'लाइव्ह रिजल्ट', 'मल्टीपल-चॉइस'] },
      { icon: '🤝', title: 'कम्युनिटी हेल्प', href: '/features/community-help', category: 'Community', tier: 'फ्री', badge: '', badgeColor: '', desc: 'शेजाऱ्यापासून शेजारी मार्केटप्लेस — प्लंबर, ट्यूटर, कुक आणि अधिक शेअर करा.', highlights: ['8 हेल्प श्रेण्या', 'रहिवासी रिव्ह्यू', 'पोस्ट आणि रिअॅक्ट'] },
      { icon: '🏊', title: 'अमेनिटी बुकिंग', href: '/features/amenities', category: 'Facilities', tier: 'प्रो', badge: 'प्रो', badgeColor: 'bg-amber/15 text-amber', desc: 'टाइम-स्लॉट निवड, डिपॉझिट हँडलिंग आणि अॅडमिन मंजुरीसह क्लबहाऊस, जिम किंवा कोर्ट बुक करा.', highlights: ['स्लॉट शेड्यूलर', 'डिपॉझिट कलेक्शन', 'अॅडमिन मंजुरी फ्लो'] },
      { icon: '🅿️', title: 'पार्किंग व्यवस्थापन', href: '/features/parking', category: 'Facilities', tier: 'स्टँडर्ड', badge: '', badgeColor: '', desc: 'वाहन रजिस्टर, स्लॉट वाटप, गेस्ट पार्किंग परवाने, दुचाकी रेकॉर्ड.', highlights: ['स्लॉट वाटप', 'गेस्ट परवाने', 'वाहन रजिस्टर'] },
      { icon: '👥', title: 'मेम्बर व्यवस्थापन', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'रहिवासी प्रवेश मंजुरी, फ्लॅट-टू-मेम्बर मॅपिंग, एका फ्लॅटमध्ये अनेक सदस्य.', highlights: ['मंजुरी वर्कफ्लो', 'फ्लॅट मॅपिंग', 'मल्टी-फॅमिली'] },
      { icon: '🛡️', title: 'कमिटी RBAC', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'ट्रेझरर, सचिव, सिक्युरिटी हेड यांना सूक्ष्म परवानग्या द्या — प्रत्येकाला फक्त आवश्यक तेच दिसेल.', highlights: ['6 प्रीसेट रोल', 'मॉड्यूल-लेव्हल परवानग्या', 'कस्टम रोल'] },
      { icon: '🔗', title: 'इन्वाइट लिंक आणि QR', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'QR code किंवा link शेअर करा, ज्यामुळे रहिवासी स्वतःहून pre-filled self-register करू शकतात. 7 दिवसाची वैधता.', highlights: ['QR code + link', 'Pre-filled form', '7-day validity'] },
      { icon: '🏘️', title: 'मल्टी-सोसायटी', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'एकाच लॉगिनने अनेक सोसायट्या व्यवस्थापित करा किंवा там राहा. एक टॅपने context बदला.', highlights: ['Instant switch', 'Separate permissions', 'Unified inbox'] },
      { icon: '📦', title: 'सब्सक्रिप्शन प्लान', href: '/pricing', category: 'Admin', tier: 'सर्व', badge: '', badgeColor: '', desc: 'फ्री, स्टँडर्ड, प्रो आणि एंटरप्राईझ प्लान — अॅपमध्ये अपग्रेड, विक्री कॉलची गरज नाही.', highlights: ['फ्री फोरएव्हर टियर', 'मासिक बिलिंग', 'तत्काळ अपग्रेड'] },
      { icon: '🔔', title: 'पुश नोटिफिकेशन्स', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'विजिटर आगमन, बिल देय, नोटिस पोस्ट, तक्रार अपडेटसाठी रिअल-टाइम अलर्ट.', highlights: ['तत्काळ डिलिव्हरी', 'Per-event control', 'दैनिक डाइजेस्ट'] },
      { icon: '📋', title: 'ऑडिट लॉग', href: '/features', category: 'Admin', tier: 'स्टँडर्ड', badge: '', badgeColor: '', desc: 'प्रत्येक अॅडमिन कृतीसाठी tamper-evident activity log — approve, reject, publish, delete.', highlights: ['Immutable log', 'Export CSV', 'Per-user filter'] },
      { icon: '🌐', title: 'मल्टीलिंगुआल UI', href: '/features', category: 'Admin', tier: 'फ्री', badge: 'भारत-प्रथम', badgeColor: 'bg-amber/15 text-amber', desc: 'संपूर्ण अॅप इंग्लिश, हिंदी, गुजराती, तमिळ, मराठी आणि पंजाबीमध्ये.', highlights: ['6 भाषा', 'तत्काळ स्विच', 'RTL-तयार'] },
      { icon: '🏢', title: 'सोसायटी रजिस्ट्रेशन', href: '/register', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'सेक्रेटरी ऑनलाइन रजिस्टर करतो, सुपरअॅडमिन मंजुरी देतो, क्रेडेन्शिअल्स त्वरित ईमेल होतात. 5 मिनिटांत लाइव.', highlights: ['ऑनलाइन रजिस्ट्रेशन', 'ऑटो मंजुरी ईमेल', 'शुरू करण्यासाठी फ्री'] },
      { icon: '⚙️', title: 'प्रोफाइल आणि सेटिंग्स', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'नोटिफिकेशन प्राधान्य, भाषा सिलेक्टर, पासवर्ड बदलणे, फ्लॅट तपशील — सर्व अॅपमध्ये.', highlights: ['Notification control', 'Language switch', 'In-app settings'] },
      { icon: '📨', title: 'नोटिफिकेशन डाइजेस्ट', href: '/features', category: 'Admin', tier: 'फ्री', badge: '', badgeColor: '', desc: 'विश्वासार्ह विजिटर एंट्रीसाठी दैनिक 9 PM डाइजेस्ट — एक नोटिफिकेशन, दहा नाही.', highlights: ['9 PM daily', 'Trusted visitors only', 'Reduces noise'] },
    ],
  },
  pa: {
    modules: [
      { icon: '🚪', title: 'ਵਿਜ਼ਿਟਰ ਮੈਨੇਜਮੈਂਟ', href: '/features/visitor-management', category: 'Security', tier: 'ਫ੍ਰੀ', badge: 'ਸਭ ਤੋਂ ਪਸੰਦੀਦਾ', badgeColor: 'bg-green/15 text-green', desc: 'OTP-ਅਧਾਰਿਤ ਗੇਟ ਐਂਟਰੀ, ਪਹਿਲਾਂ ਤੋਂ ਮਨਜ਼ੂਰ ਪਾਸ਼, ਭਰੋਸੇਮੰਦੀ maid ਅਤੇ drivers — ਬਿਨਾਂ ਕਿਸੇ ਹਾਰਡਵੇਅਰ ਦੇ ਪੂਰਾ ਗੇਟ ਲੌਗ।', highlights: ['4 ਵਿਜ਼ਿਟਰ ਫਲੋ', 'ਕੋਈ ਹਾਰਡਵੇਅਰ ਨਹੀਂ', 'ਆਟੋ ਡਿਲੀਵਰੀ ਐਗਜ਼ਿਟ ਟਾਈਮਰ'] },
      { icon: '👮', title: 'ਸੁਰੱਖਿਆ ਗਾਰਦ ਪੋਰਟਲ', href: '/features/visitor-management', category: 'Security', tier: 'ਫ੍ਰੀ', badge: '', badgeColor: '', desc: 'ਗਾਰਡਾਂ ਲਈ ਵੱਖਰਾ UX — walk-in ਲਾਗਿੰਗ, OTP ਪੁਸ਼ਟੀ, trusted-pass check-in.', highlights: ['ਰੈਜ਼ਿਡੈਂਟਸ ਵਰਗਾ ਹੀ ਐਪ', 'Walk-in + OTP ਫਲੋ', 'ਰੀਅਲ-ਟਾਈਮ ਮਨਜ਼ੂਰੀ'] },
      { icon: '💸', title: 'ਮਾਂਟੇਨੈਂਸ ਅਤੇ ਬਿਲਿੰਗ', href: '/features/maintenance', category: 'Finance', tier: 'ਫ੍ਰੀ', badge: 'ਫ੍ਰੀ ਟਾਇਰ', badgeColor: 'bg-teal/15 text-teal', desc: 'ਮਾਸਿਕ ਬਿਲ ਆਪਣੇ-ਆਪ ਬਣਾਓ, UPI/ਨਕਦ/NEFT ਨਾਲ ਪੇਮੈਂਟ ਟਰੈਕ ਕਰੋ, defaulters ਪਛਾਣੋ।', highlights: ['ਆਟੋ ਬਿਲ ਜਨਰੇਸ਼ਨ', 'ਡਿਫਾਲਟਰ ਰਿਪੋਰਟ', 'ਡਿਜ਼ਿਟਲ ਰਸੀਦ'] },
      { icon: '📊', title: 'ਭੁਗਤਾਨ ਵਿਸ਼ਲੇਸ਼ਣ', href: '/features/maintenance', category: 'Finance', tier: 'ਸਟੈਂਡਰਡ', badge: '', badgeColor: '', desc: 'ਕਲੈਕਸ਼ਨ ਰੇਟ, ਮਹੀਨੇ-ਦੁਆਰਾ ਟ੍ਰੈਂਡ, ਬਕਾਇਆ ਰਕਮ ਇੱਕ ਨਜ਼ਰ ਵਿੱਚ।', highlights: ['ਕਲੈਕਸ਼ਨ ਡੈਸ਼ਬੋਰਡ', 'ਟ੍ਰੈਂਡ ਚਾਰਟ', 'ਰਿਪੋਰਟ ਐਕਸਪੋਰਟ'] },
      { icon: '📢', title: 'ਨੋਟੀਸ ਬੋਰਡ', href: '/features/notices', category: 'Community', tier: 'ਫ੍ਰੀ', badge: '', badgeColor: '', desc: 'ਪਿਨ ਕੀਤੀਆਂ ਨੋਟੀਸ, push ਡਿਲੀਵਰੀ, ਕੈਟੇਗੋਰੀ ਟੈਗ, read-receipts.', highlights: ['ਸਾਰੇ ਰਹਿਣ ਵਾਲਿਆਂ ਤੱਕ push', '5 ਟੈਗ ਕਿਸਮਾਂ', 'ਪਿਨ ਅਤੇ ਸ਼ੈੱਡਿਊਲ'] },
      { icon: '🛠️', title: 'ਮੁਸ਼ਕਲਾਂ ਅਤੇ ਸ਼ਿਕਾਇਤਾਂ', href: '/features/issues', category: 'Community', tier: 'ਸਟੈਂਡਰਡ', badge: '', badgeColor: '', desc: 'ਫ਼ੋਟੋਆਂ ਨਾਲ ਸ਼ਿਕਾਇਤਾਂ ਦਰਜ ਕਰੋ, vendors ਨੂੰ ਅਸਾਈਨ ਕਰੋ, open ਤੋਂ resolved ਤੱਕ ਸਥਿਤੀ ਟਰੈਕ ਕਰੋ।', highlights: ['ਫ਼ੋਟੋ ਅਟੈਚਮੈਂਟ', 'ਵੈਂਡਰ ਅਸਾਈਨਮੈਂਟ', 'ਪੂਰਾ ਆਡੀਟ ਟਰੈਲ'] },
      { icon: '🎉', title: 'ਈਵੈਂਟਸ ਅਤੇ ਪੋਲ', href: '/features/events', category: 'Community', tier: 'ਸਟੈਂਡਰਡ', badge: '', badgeColor: '', desc: 'RSVP, ਕੈਲੰਡਰ ਐਕਸਪੋਰਟ, ਫ਼ੋਟੋ ਗੈਲਰੀ ਅਤੇ ਵੋਟਿੰਗ ਪੋਲਾਂ ਨਾਲ ਸੋਸਾਈਟੀ ਇਵੈਂਟਸ।', highlights: ['RSVP ਟਰੈਕਿੰਗ', 'ਅਣਜਾਣ ਪੋਲ', 'ਫ਼ੋਟੋ ਗੈਲਰੀ'] },
      { icon: '🗳️', title: 'ਕਮਿਊਨਿਟੀ ਪੋਲ', href: '/features/events', category: 'Community', tier: 'ਸਟੈਂਡਰਡ', badge: '', badgeColor: '', desc: 'ਸੋਸਾਈਟੀ ਦੇ ਫੈਸਲੇ ਨੂੰ ਵੋਟ ਵਿੱਚ ਬਦਲੋ — ਅਣਜਾਣ ਜਾਂ ਨਾਮੀ, live result charts ਨਾਲ।', highlights: ['ਅਣਜਾਣ ਵੋਟਿੰਗ', 'ਲਾਈਵ ਰਿਜ਼ਲਟ', 'ਮਲਟੀਪਲ-ਚੋਇਸ'] },
      { icon: '🤝', title: 'ਕਮਿਊਨਿਟੀ ਹੈਲਪ', href: '/features/community-help', category: 'Community', tier: 'ਫ੍ਰੀ', badge: '', badgeColor: '', desc: 'ਗੁਆਂਢੀ-ਸੈ-ਗੁਆਂਢੀ ਮਾਰਕੀਟਪਲੇਸ — ਪਲੰਬਰ, ਟਿਊਟਰ, ਕੂਕ ਅਤੇ ਹੋਰ ਬਹੁਤ ਕੁਝ ਸਾਂਝਾ ਕਰੋ।', highlights: ['8 ਹੈਲਪ ਕੈਟਾਗਰੀਜ਼', 'ਰਿਹਾਇਸ਼ੀ ਰਿਵਿਊ', 'ਪੋਸਟ ਅਤੇ ਜਵਾਬ'] },
      { icon: '🏊', title: 'ਅਮੀਨਿਟੀ ਬੁਕਿੰਗ', href: '/features/amenities', category: 'Facilities', tier: 'ਪ੍ਰੋ', badge: 'ਪ੍ਰੋ', badgeColor: 'bg-amber/15 text-amber', desc: 'ਟਾਈਮ-ਸਲਾਟ ਚੋਣ, ਡਿਪਾਜ਼ਿਟ ਹੈਂਡਲਿੰਗ ਅਤੇ ਐਡਮਿਨ ਮਨਜ਼ੂਰੀ ਨਾਲ ਕਲਬਹਾ House, ਜਿਮ ਜਾਂ ਕੋਰਟ ਬੁੱਕ ਕਰੋ।', highlights: ['ਸਲਾਟ ਸ਼ੇਡਿਊਲਰ', 'ਡਿਪਾਜ਼ਿਟ ਕਲੈਕਸ਼ਨ', 'ਐਡਮਿਨ ਮਨਜ਼ੂਰੀ ਫਲੋ'] },
      { icon: '🅿️', title: 'ਪਾਰਕਿੰਗ ਮੈਨੇਜਮੈਂਟ', href: '/features/parking', category: 'Facilities', tier: 'ਸਟੈਂਡਰਡ', badge: '', badgeColor: '', desc: 'ਵਾਹਨ ਰਜਿਸਟਰੀ, ਸਲਾਟ ਆਲੋਕਣ, ਗੈਸਟ ਪਾਰਕਿੰਗ ਪਰਮਿਟ, ਦੋ-ਚੱਕਰ ਰਿਕਾਰਡ।', highlights: ['ਸਲਾਟ ਆਲੋਕਣ', 'ਗੈਸਟ ਪਰਮਿਟ', 'ਵਾਹਨ ਰਜਿਸਟਰੀ'] },
      { icon: '👥', title: 'ਮੈਂਬਰ ਮੈਨੇਜਮੈਂਟ', href: '/features', category: 'Admin', tier: 'ਫ੍ਰੀ', badge: '', badgeColor: '', desc: 'ਰਹਿਣ ਵਾਲਿਆਂ ਦੀ ਸ਼ਾਮਲਗੀ ਮਨਜ਼ੂਰੀ, ਫਲੈਟ-ਟੂ-ਮੈਂਬਰ ਮੈਪਿੰਗ, ਇੱਕ ਫਲੈਟ ਤੇ ਕੇਵਲ ਬਹੁਤ ਸੇ ਮੈਂਬਰ।', highlights: ['ਮਨਜ਼ੂਰੀ ਵਾਰਕਫਲੋ', 'ਫਲੈਟ ਮੈਪਿੰਗ', 'ਮਲਟੀ-ਫੈਮਿਲੀ'] },
      { icon: '🛡️', title: 'ਕਮੇਟੀ RBAC', href: '/features', category: 'Admin', tier: 'ਫ੍ਰੀ', badge: '', badgeColor: '', desc: 'ਟ੍ਰੈਜ਼ਰਰ, ਸਕੱਤਰ, ਸੁਰੱਖਿਆ ਅਧਿਕਾਰੀ ਨੂੰ ਨੁਕਸਦਾਰ ਇਜਾਜ਼ਤਾਂ ਸੌਂਪੋ — ਹਰੇਕ ਨੂੰ ਸਿਰਫ ਉਹੀ ਵੇਖਣ ਨੂੰ ਮਿਲੇ ਜੋ ਉਸ ਨੂੰ ਚਾਹੀਦਾ ਹੈ।', highlights: ['6 ਪ੍ਰੀਸੈਟ ਰੋਲ', 'ਮੌਡਿਊਲ-ਲੇਵਲ ਪਰਮਿਸ਼ਨ', 'ਕਸਟਮ ਰੋਲ'] },
      { icon: '🔗', title: 'ਆਮੰਤਰ ਲਿੰਕ ਅਤੇ QR', href: '/features', category: 'Admin', tier: 'ਫ੍ਰੀ', badge: '', badgeColor: '', desc: 'QR code ਜਾਂ link ਸਾਂਝਾ ਕਰੋ ਤਾਂ ਕਿ ਰਹਿਣ ਵਾਲੇ ਆਪਣੇ-ਆਪ pre-filled self-register ਕਰ ਸਕਣ। 7 ਦਿਨ ਦੀ ਮਿਆਦ।', highlights: ['QR code + link', 'Pre-filled form', '7-day validity'] },
      { icon: '🏘️', title: 'ਮਲਟੀ-ਸੋਸਾਇਟੀ', href: '/features', category: 'Admin', tier: 'ਫ੍ਰੀ', badge: '', badgeColor: '', desc: 'ਇੱਕ ਲਾਗਇਨ ਨਾਲ ਕਈ ਸੋਸਾਇਟੀਆਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋਂ ਜਾਂ ਉਥੇ ਰਹਿਣ। ਇੱਕ ਟੈਪ ਨਾਲ context ਬਦਲੋ।', highlights: ['Instant switch', 'Separate permissions', 'Unified inbox'] },
      { icon: '📦', title: 'ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਪਲਾਨ', href: '/pricing', category: 'Admin', tier: 'ਸਾਰੇ', badge: '', badgeColor: '', desc: 'ਫ੍ਰੀ, ਸਟੈਂਡਰਡ, ਪ੍ਰੋ ਅਤੇ ਐਂਟਰਪ੍ਰਾਈਜ਼ ਪਲਾਨ — ਐਪ ਵਿੱਚ ਅਪਗਰੇਡ, ਕੋਈ ਸੇਲਜ਼ ਕਾਲ ਨਹੀਂ।', highlights: ['ਫ੍ਰੀ ਫੋਰਏਵਰ ਟਾਇਰ', 'ਮਾਸਿਕ ਬਿਲਿੰਗ', 'ਤੁਰੰਤ ਅਪਗ੍ਰੇਡ'] },
      { icon: '🔔', title: 'ਪੁਸ਼ ਅਧੀਨਗੀ', href: '/features', category: 'Admin', tier: 'ਫ੍ਰੀ', badge: '', badgeColor: '', desc: 'ਵਿਜ਼ਿਟਰ ਆਉਣ, ਬਿਲ ਦੀ ਮਿਆਦ, ਨੋਟੀਸ ਪੋਸਟ, ਸ਼ਿਕਾਇਤ ਅਪਡੇਟ ਲਈ ਰੀਅਲ-ਟਾਈਮ ਅਲਰਟ।', highlights: ['ਤੁਰੰਤ ਡਿਲੀਵਰੀ', 'Per-event control', 'ਦਿਨਕਾ ਡਾਈਜੈਸਟ'] },
      { icon: '📋', title: 'ਆਡੀਟ ਲੌਗ', href: '/features', category: 'Admin', tier: 'ਸਟੈਂਡਰਡ', badge: '', badgeColor: '', desc: 'ਹਰ ਐਡਮਿਨ ਕਾਰਵਾਈ ਲਈ tamper-evident activity log — approve, reject, publish, delete.', highlights: ['Immutable log', 'Export CSV', 'Per-user filter'] },
      { icon: '🌐', title: 'ਮਲਟੀਲਿੰਗੁਅਲ UI', href: '/features', category: 'Admin', tier: 'ਫ੍ਰੀ', badge: 'ਭਾਰਤ-ਪਹਿਲਾਂ', badgeColor: 'bg-amber/15 text-amber', desc: 'ਪੂਰੀ ਐਪ ਅੰਗਰੇਜ਼ੀ, ਹਿੰਦੀ, ਗੁਜਰਾਤੀ, ਤਾਮਿਲ, ਮਰਾਠੀ ਅਤੇ ਪੰਜਾਬੀ ਵਿੱਚ।', highlights: ['6 ਭਾਸ਼ਾਵਾਂ', 'ਤੁਰੰਤ ਸਵਿਚ', 'RTL-ਤਿਆਰ'] },
      { icon: '🏢', title: 'ਸੋਸਾਇਟੀ ਰਜਿਸਟ੍ਰੇਸ਼ਨ', href: '/register', category: 'Admin', tier: 'ਫ੍ਰੀ', badge: '', badgeColor: '', desc: 'ਸੈਕਰੇਟਰੀ ਆਨਲਾਈਨ ਰਜਿਸਟਰ ਕਰਦਾ ਹੈ, ਸੁਪਰਐਡਮਿਨ ਮਨਜ਼ੂਰੀ ਦਿੰਦਾ ਹੈ, credentials ਤੁਰੰਤ ਈਮੇਲ ਹੁੰਦੇ ਹਨ। 5 ਮਿੰਟਾਂ ਵਿੱਚ ਲਾਈਵ।', highlights: ['Online registration', 'Auto approval email', 'Free to start'] },
      { icon: '⚙️', title: 'ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਸੈਟਿੰਗਸ', href: '/features', category: 'Admin', tier: 'ਫ੍ਰੀ', badge: '', badgeColor: '', desc: 'ਨੋਟੀਫਿਕੇਸ਼ਨ ਪਸੰਦ, ਭਾਸ਼ਾ ਚੋਣਕਾਰ, ਪਾਸਵਰਡ ਬਦਲਣਾ, ਫਲੈਟ ਵੇਰਵਾ — ਸਾਰੇ ਐਪ ਵਿੱਚ।', highlights: ['Notification control', 'Language switch', 'In-app settings'] },
      { icon: '📨', title: 'ਨੋਟੀਫਿਕੇਸ਼ਨ ਡਾਈਜੈਸਟ', href: '/features', category: 'Admin', tier: 'ਫ੍ਰੀ', badge: '', badgeColor: '', desc: 'ਭਰੋਸੇਮੰਦ ਵਿਜ਼ਿਟਰ ਐਂਟਰੀਆਂ ਲਈ ਰੋਜ਼ਾਨਾ 9 PM ਡਾਈਜੈਸਟ — ਇੱਕ ਨੋਟੀਫਿਕੇਸ਼ਨ, ਦੱਸ ਨਹੀਂ।', highlights: ['9 PM daily', 'Trusted visitors only', 'Reduces noise'] },
    ],
  },
};

export function getHomeFeaturesContent(locale: Locale): HomeFeaturesContent {
  return (content[locale] ?? content.en) as HomeFeaturesContent;
}
