// home/claude/societyapp-build/app/faq/page.tsx
"use client";
import { useState } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Link from "next/link";

const categories = [
  {
    id: "getting-started",
    label: "Getting Started",
    icon: "🚀",
    faqs: [
      { q: "How do I register my society on SocietyApp?", a: "Go to societyapp.in/register and fill in your society name, city, number of units, and your contact details. Our team reviews and approves your society usually within 24 hours. You'll receive your admin credentials by email." },
      { q: "How long does it take to go live?", a: "Most societies are fully live within 5 minutes of approval. You add your flats, invite your first resident, and your gate guard can start logging visitors immediately. No tech expertise required." },
      { q: "Do residents need to download the app?", a: "Yes, residents download SocietyApp (iOS or Android) and enter the join code or scan the QR generated by the admin. Once approved, they get full access to notices, visitor approvals, and maintenance bills." },
      { q: "What languages does SocietyApp support?", a: "SocietyApp is available in English, Hindi, Gujarati, Tamil, Marathi, and Punjabi. Each user can choose their preferred language independently — the secretary can use Gujarati while a resident uses English." },
      { q: "Can I migrate from MyGate or ApnaComplex?", a: "Yes. Our onboarding team provides a migration guide. Resident data can be imported via CSV. Visitor history from other platforms cannot be imported, but your gate log starts fresh from day one on SocietyApp." },
    ],
  },
  {
    id: "visitor",
    label: "Visitor Management",
    icon: "🚪",
    faqs: [
      { q: "Does Visitor Management require any hardware at the gate?", a: "No hardware whatsoever. The security guard uses the same SocietyApp on their existing Android smartphone. No QR scanners, RFID readers, or intercom systems are needed." },
      { q: "What if a visitor arrives without an OTP?", a: "The guard uses the Walk-In flow — logs the visitor name and host flat, sends a push notification to the resident, and waits for approval or rejection. This takes under 30 seconds." },
      { q: "Can I give a standing pass to my maid or cook?", a: "Yes. The Trusted Visitor flow lets you register frequent visitors with daily, monthly, or permanent passes. You can restrict entry to specific days and time windows (e.g., Mon–Fri, 8–10 AM only)." },
      { q: "How long are OTPs valid?", a: "OTPs generated by the Pre-Approved Invite flow are valid for 24 hours or 2 hours after the expected arrival time (whichever comes first). Residents can cancel an invite at any time before it's used." },
      { q: "Can the guard see visitor history?", a: "Yes. Guards can view today's gate log. Admins can view and export full gate history with timestamps, guard names, resident approvals, and visitor details." },
    ],
  },
  {
    id: "billing",
    label: "Billing & Maintenance",
    icon: "💸",
    faqs: [
      { q: "How does maintenance billing work?", a: "The admin creates a bill with name, amount, and due date, then publishes it to all residents. Residents see the bill in their app and can pay via the recorded method. The admin marks payments as received and receipts are auto-generated." },
      { q: "Can I charge different amounts for different flats?", a: "Yes. You can create flat-specific bill amounts. For example, 2BHK flats can be charged ₹2,500 and 3BHK flats ₹3,500. You can also create one-time special levy bills." },
      { q: "How do I track who hasn't paid?", a: "The Defaulters Report shows all unpaid and overdue bills by flat, resident name, and amount. You can send automated reminders directly from the report screen." },
      { q: "Does SocietyApp process payments?", a: "SocietyApp is a records and communication platform, not a payment processor. Residents pay via UPI, NEFT, or cash as usual, and the admin marks the payment as received in the app. A payment gateway integration is on the Pro+ roadmap." },
    ],
  },
  {
    id: "security",
    label: "Security & Privacy",
    icon: "🔐",
    faqs: [
      { q: "Where is resident data stored?", a: "All data is stored on servers located within India, in compliance with Indian data protection laws. We use encrypted storage and never sell or share resident data with third parties." },
      { q: "Can residents see other residents' data?", a: "No. Residents can see the community directory (name and flat number only) if the admin enables it. Payment data, contact numbers, and visitor logs are only visible to the relevant resident and admins." },
      { q: "What happens to our data if we cancel?", a: "You can export all your society data (residents, bills, gate logs) as CSV before cancelling. After 90 days of account closure, data is permanently deleted from our servers." },
      { q: "Is SocietyApp GDPR compliant?", a: "Yes. SocietyApp follows GDPR principles and India's PDPB (Personal Data Protection Bill) guidelines. We have a clear data processing agreement available for Enterprise customers." },
    ],
  },
  {
    id: "pricing",
    label: "Pricing",
    icon: "💳",
    faqs: [
      { q: "Is the Free plan really free forever?", a: "Yes. The Free plan is permanently free for societies up to 50 units. There is no trial expiry, no credit card required, and no hidden charges. Visitor Management, Notice Board, and Basic Billing are included." },
      { q: "Do you charge per flat / per unit?", a: "No per-unit pricing below 200 units. The Standard plan is a flat ₹2,999/month for any society up to 200 units. You're not penalised for growing your resident base within the limit." },
      { q: "Can I upgrade or downgrade anytime?", a: "Upgrades take effect immediately. Downgrades take effect at the end of your billing period. All data is preserved during plan changes." },
      { q: "Is there a refund policy?", a: "All paid plans come with a 30-day money-back guarantee. If you're not satisfied within 30 days, contact us and we'll issue a full refund, no questions asked." },
    ],
  },
  {
    id: "technical",
    label: "Technical",
    icon: "⚙️",
    faqs: [
      { q: "Which devices does the app support?", a: "SocietyApp runs on Android 8.0+ and iOS 14+. The web panel works on all modern browsers (Chrome, Safari, Firefox, Edge). There is no Windows or desktop app — the web panel covers admin tasks on laptop/PC." },
      { q: "Does SocietyApp work offline?", a: "Core features like viewing notices and checking your visitor log work offline with cached data. Logging new visitors and sending notifications require an active internet connection." },
      { q: "Does SocietyApp have an API?", a: "Yes. API access is available on the Pro plan. Our REST API allows integration with accounting software, CCTV systems, and custom dashboards. Documentation is available at docs.societyapp.in." },
      { q: "Can I white-label SocietyApp for my builder / developer brand?", a: "Yes, on the Enterprise plan. We offer full white-labelling including custom app name, icon, splash screen, and colour scheme. Contact our sales team for a quote." },
      { q: "How often is the app updated?", a: "We release updates every 2–3 weeks on both Android and iOS. Updates are automatic. Major feature releases are announced via the in-app notice board and our blog." },
    ],
  },
];

export default function FaqPage() {
  const [search, setSearch] = useState("");
  const [activeCategory, setActiveCategory] = useState("getting-started");

  const filtered = categories.map(cat => ({
    ...cat,
    faqs: cat.faqs.filter(
      f => f.q.toLowerCase().includes(search.toLowerCase()) || f.a.toLowerCase().includes(search.toLowerCase())
    ),
  })).filter(cat => cat.faqs.length > 0);

  const displayed = search ? filtered : categories.filter(c => c.id === activeCategory);

  return (
    <>
      <Navbar />
      <main className="bg-light min-h-screen pt-16">

        {/* ── Hero ── */}
        <section className="bg-navy py-20 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-[400px] h-[400px] rounded-full bg-teal/10 blur-[100px] pointer-events-none" />
          <div className="max-w-3xl mx-auto px-5 text-center">
            <div className="inline-block bg-teal/20 text-teal text-xs font-bold uppercase tracking-widest px-3 py-1.5 rounded-full mb-5">FAQ</div>
            <h1 className="font-display text-4xl md:text-5xl font-bold text-white mb-4">Frequently Asked Questions</h1>
            <p className="text-white/60 text-lg mb-8">Find answers to the most common questions about SocietyApp.</p>
            <div className="relative">
              <input
                type="text"
                value={search}
                onChange={e => setSearch(e.target.value)}
                placeholder="Search questions... e.g. 'OTP' or 'payment'"
                className="w-full bg-white/10 border border-white/20 rounded-2xl px-5 py-4 text-white placeholder-white/40 text-sm focus:outline-none focus:border-teal transition-colors"
              />
              <span className="absolute right-4 top-1/2 -translate-y-1/2 text-white/30 text-xl">🔍</span>
            </div>
          </div>
          <div className="absolute bottom-0 left-0 right-0">
            <svg viewBox="0 0 1440 30" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M0 30L1440 30L1440 5C1200 25 720 0 0 15L0 30Z" fill="#F4F6F8" />
            </svg>
          </div>
        </section>

        {/* ── Category nav + content ── */}
        <section className="max-w-5xl mx-auto px-5 py-12">
          {!search && (
            <div className="flex flex-wrap gap-2 mb-8">
              {categories.map(cat => (
                <button
                  key={cat.id}
                  onClick={() => setActiveCategory(cat.id)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-full text-sm font-semibold transition-colors ${
                    activeCategory === cat.id
                      ? "bg-teal text-white"
                      : "bg-white border border-gray-200 text-gray-600 hover:border-teal/40"
                  }`}
                >
                  <span>{cat.icon}</span> {cat.label}
                </button>
              ))}
            </div>
          )}

          {search && filtered.length === 0 && (
            <div className="text-center py-16">
              <div className="text-5xl mb-4">🤔</div>
              <p className="text-navy font-display font-bold text-xl mb-2">No results for "{search}"</p>
              <p className="text-gray-500 mb-6">Try different keywords or browse categories below.</p>
              <button onClick={() => setSearch("")} className="text-teal font-semibold text-sm hover:underline">Clear search</button>
            </div>
          )}

          {displayed.map(cat => (
            <div key={cat.id} className="mb-8">
              {search && (
                <h2 className="font-display font-bold text-navy text-xl mb-4 flex items-center gap-2">
                  {cat.icon} {cat.label}
                </h2>
              )}
              <div className="space-y-3">
                {cat.faqs.map((faq, i) => (
                  <details key={i} className="group bg-white border border-gray-100 rounded-2xl overflow-hidden shadow-sm">
                    <summary className="px-5 py-4 font-semibold text-navy cursor-pointer list-none flex items-start justify-between gap-3">
                      <span className="leading-relaxed">{faq.q}</span>
                      <span className="text-teal text-xl group-open:rotate-45 transition-transform flex-shrink-0 mt-0.5">+</span>
                    </summary>
                    <p className="px-5 pb-5 text-gray-500 text-sm leading-relaxed border-t border-gray-50 pt-3">{faq.a}</p>
                  </details>
                ))}
              </div>
            </div>
          ))}

          {/* Still need help */}
          <div className="mt-12 bg-navy rounded-3xl p-8 text-center">
            <div className="text-4xl mb-4">💬</div>
            <h3 className="font-display text-2xl font-bold text-white mb-2">Still have questions?</h3>
            <p className="text-white/50 mb-6">Our team answers on WhatsApp within 2 hours on weekdays.</p>
            <div className="flex flex-col sm:flex-row gap-3 justify-center">
              <Link href="/contact" className="inline-flex items-center justify-center gap-2 px-6 py-3 rounded-xl bg-teal text-white font-semibold text-sm hover:bg-teal/90 transition-colors">
                Contact Us
              </Link>
              <a
                href="https://wa.me/919876543210"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center justify-center gap-2 px-6 py-3 rounded-xl bg-white/10 border border-white/20 text-white font-semibold text-sm hover:bg-white/20 transition-colors"
              >
                💬 WhatsApp Us
              </a>
            </div>
          </div>
        </section>

      </main>
      <Footer />
    </>
  );
}